'use strict'

module.exports = {
  id: "captured-mentat",
  name: "Captured Mentat",
  source: "Uprising",
  compatibility: "All",
  count: 1,
  persuasionCost: 5,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [
    "green",
    "yellow"
  ],
  factionAccess: [],
  spyAccess: false,
  agentAbility: "Discard 1 card →\n· +1 Intrigue card\n· Draw 1 card",
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: "-1 Influence with a Faction -> +1 Influence with a Faction",
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: false,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
