'use strict'

module.exports = {
  id: "guild-spy",
  name: "Guild Spy",
  source: "Uprising",
  compatibility: "Uprising",
  count: 1,
  persuasionCost: 3,
  acquisitionBonus: "+1 Spy",
  passiveAbility: null,
  agentIcons: [],
  factionAccess: [],
  spyAccess: true,
  agentAbility: "Discard 1 card → Draw 1 card\nIf you discarded a Spacing Guild card:\n· +1 Intrigue card",
  revealPersuasion: 2,
  revealSwords: 0,
  revealAbility: "If you acquire The Spice Must Flow this turn:\n· Gain one influence with each Faction you are spying on",
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: false,
  hasSpies: true,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
