'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const sardaukar_canny = require('./sardaukar-canny.js')
const sardaukar_charismatic = require('./sardaukar-charismatic.js')
const sardaukar_desperate = require('./sardaukar-desperate.js')
const sardaukar_driven = require('./sardaukar-driven.js')
const sardaukar_fierce = require('./sardaukar-fierce.js')
const sardaukar_loyal = require('./sardaukar-loyal.js')

module.exports = [
  sardaukar_canny,
  sardaukar_charismatic,
  sardaukar_desperate,
  sardaukar_driven,
  sardaukar_fierce,
  sardaukar_loyal,
]
