const cardData = [
  require('./HolmegaardBows.js'),
  require('./PapyrusofAni.js'),
  require('./PavlovianTusk.js'),
  require('./DancingGirl.js'),
  require('./LurganCanoe.js'),
  require('./XianrendongShards.js'),
  require('./PriestKing.js'),
  require('./ElectrumStaterofEfesos.js'),
  require('./JiskairumokoNecklace.js'),
  require('./TreatyofKadesh.js'),
  require('./SibiduNeedle.js'),
  require('./BasurHoyukTokens.js'),
  require('./MaskofWarka.js'),
  require('./ArkoftheCovenant.js'),
  require('./TaleoftheShipwreckedSailor.js'),
  require('./ChronicleofZuo.js'),
  require('./BabylonianChronicles.js'),
  require('./HolyGrail.js'),
  require('./TerracottaArmy.js'),
  require('./HolyLance.js'),
  require('./BaghdadBattery.js'),
  require('./SeikilosEpitaph.js'),
  require('./RosettaStone.js'),
  require('./DeadSeaScrolls.js'),
  require('./CyrusCylinder.js'),
  require('./Excalibur.js'),
  require('./MjolnirAmulet.js'),
  require('./MoyloughBeltShrine.js'),
  require('./AlongtheRiverduringtheQingmingFestival.js'),
  require('./PhilosophersStone.js'),
  require('./IfeHead.js'),
  require('./DunhuangStarChart.js'),
  require('./YataNoKagami.js'),
  require('./Necronomicon.js'),
  require('./ShroudofTurin.js'),
  require('./EastIndiaCompanyCharter.js'),
  require('./GalleonNuestraSenoraDeAtocha.js'),
  require('./Moses.js'),
  require('./MonaLisa.js'),
  require('./MolassesReefCaravel.js'),
  require('./HuntLennoxGlobe.js'),
  require('./PetitionofRight.js'),
  require('./DelftPocketTelescope.js'),
  require('./CrossofCoronado.js'),
  require('./AbellGalleryHarpsichord.js'),
  require('./GalleyWhydah.js'),
  require('./ShipoftheLineSussex.js'),
  require('./GujinTushuJinsheng.js'),
  require('./TheDailyCourant.js'),
  require('./BaroqueLonguelaBelle.js'),
  require('./HudsonsBayCompanyArchives.js'),
  require('./BoerhaaveMicroscope.js'),
  require('./Principia.js'),
  require('./SandhamRoomCricketBat.js'),
  require('./AlmiraQueenoftheCastle.js'),
  require('./FrigateConstitution.js'),
  require('./USDeclarationofIndependence.js'),
  require('./QianlongsDragonRobe.js'),
  require('./PrideandPrejudice.js'),
  require('./TheWealthofNations.js'),
  require('./ButtonwoodAgreement.js'),
  require('./KilogramoftheArchives.js'),
  require('./PuffingBilly.js'),
  require('./MoonlightSonata.js'),
  require('./MarchaReal.js'),
  require('./SubmarineHLHunley.js'),
  require('./JedliksElectromagneticSelfRotor.js'),
  require('./ColtPatersonRevolver.js'),
  require('./SingerModel27.js'),
  require('./InternationalPrototypeMetreBar.js'),
  require('./HansenWritingBall.js'),
  require('./PeriodicTable.js'),
  require('./CorvetteChallenger.js'),
  require('./RoundhayGardenScene.js'),
  require('./TheCommunistManifesto.js'),
  require('./BattleshipBismark.js'),
  require('./BattleshipYamato.js'),
  require('./PlushBeweglichRodBear.js'),
  require('./ActionComics1.js'),
  require('./LinerTitanic.js'),
  require('./MeijiMuraStampVendingMachine.js'),
  require('./ParnellPitchDrop.js'),
  require('./EarhartsLockheedElectra10E.js'),
  require('./GarlandsRubySlippers.js'),
  require('./30WorldCupFinalBall.js'),
  require('./CrusaderRabbit.js'),
  require('./VelcroShoes.js'),
  require('./RockAroundtheClock.js'),
  require('./MagnavoxOdyssey.js'),
  require('./PhilipsCompactCassette.js'),
  require('./Syncom3.js'),
  require('./YeagersBellX1A.js'),
  require('./Luna3.js'),
  require('./TheBigBang.js'),
  require('./MarilynDiptych.js'),
  require('./TankerExxonValdez.js'),
  require('./Maldives.js'),
  require('./DollytheSheep.js'),
  require('./WheresWaldo.js'),
  require('./MusksTeslaRoadster.js'),
  require('./SeikanTunnel.js'),
  require('./RoverCuriosity.js'),
  require('./HiggsBoson.js'),
  require('./DeLoreanDMC12.js'),
  require('./DragonsLair.js'),
  require('./16Psyche.js'),
  require('./GreatBarrierReef.js'),
  require('./Greenland.js'),
  require('./JumboKingdom.js'),
  require('./MartianInternet.js'),
  require('./OculusQuest.js'),
  require('./PizzaPacaya.js'),
  require('./Sanskrit.js'),
  require('./TasmanianTiger.js'),
  require('./WhatDoestheFoxSay.js'),
]

function MuseumFactory(index) {
  return {
    name: 'Museum ' + index,
    shortName: 'msm' + index,
    expansion: 'arti',
    text: '',
    alt: '',
    isSpecialAchievement: false,
    isMuseum: true,
  }
}

const achievementData = [
  MuseumFactory(1),
  MuseumFactory(2),
  MuseumFactory(3),
  MuseumFactory(4),
  MuseumFactory(5),
]

module.exports = {
  cardData,
  achievementData,
}
