'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const conflict_battle_for_arrakeen_uprising = require('./conflict-battle-for-arrakeen-uprising.js')
const conflict_battle_for_arrakeen = require('./conflict-battle-for-arrakeen.js')
const conflict_battle_for_carthag = require('./conflict-battle-for-carthag.js')
const conflict_battle_for_imperial_basin_uprising = require('./conflict-battle-for-imperial-basin-uprising.js')
const conflict_battle_for_imperial_basin = require('./conflict-battle-for-imperial-basin.js')
const conflict_battle_for_spice_refinery = require('./conflict-battle-for-spice-refinery.js')
const conflict_choam_security = require('./conflict-choam-security.js')
const conflict_cloak_and_dagger = require('./conflict-cloak-and-dagger.js')
const conflict_desert_power = require('./conflict-desert-power.js')
const conflict_grand_vision = require('./conflict-grand-vision.js')
const conflict_guild_bank_raid = require('./conflict-guild-bank-raid.js')
const conflict_machinations = require('./conflict-machinations.js')
const conflict_propaganda = require('./conflict-propaganda.js')
const conflict_protect_the_sietches = require('./conflict-protect-the-sietches.js')
const conflict_raid_stockpiles = require('./conflict-raid-stockpiles.js')
const conflict_secure_imperial_basin_uprising = require('./conflict-secure-imperial-basin-uprising.js')
const conflict_secure_imperial_basin = require('./conflict-secure-imperial-basin.js')
const conflict_seize_spice_refinery = require('./conflict-seize-spice-refinery.js')
const conflict_shadow_contest = require('./conflict-shadow-contest.js')
const conflict_siege_of_arrakeen_uprising = require('./conflict-siege-of-arrakeen-uprising.js')
const conflict_siege_of_arrakeen = require('./conflict-siege-of-arrakeen.js')
const conflict_siege_of_carthag = require('./conflict-siege-of-carthag.js')
const conflict_skirmish_1 = require('./conflict-skirmish-1.js')
const conflict_skirmish_2 = require('./conflict-skirmish-2.js')
const conflict_skirmish_3 = require('./conflict-skirmish-3.js')
const conflict_skirmish_4 = require('./conflict-skirmish-4.js')
const conflict_skirmish_5 = require('./conflict-skirmish-5.js')
const conflict_skirmish_crysknife = require('./conflict-skirmish-crysknife.js')
const conflict_skirmish_desert_mouse = require('./conflict-skirmish-desert-mouse.js')
const conflict_skirmish_ornithopter = require('./conflict-skirmish-ornithopter.js')
const conflict_sort_through_the_chaos = require('./conflict-sort-through-the-chaos.js')
const conflict_spice_freighters = require('./conflict-spice-freighters.js')
const conflict_storms_in_the_south = require('./conflict-storms-in-the-south.js')
const conflict_terrible_purpose = require('./conflict-terrible-purpose.js')
const conflict_test_of_loyalty = require('./conflict-test-of-loyalty.js')
const conflict_trade_dispute = require('./conflict-trade-dispute.js')

module.exports = [
  conflict_battle_for_arrakeen_uprising,
  conflict_battle_for_arrakeen,
  conflict_battle_for_carthag,
  conflict_battle_for_imperial_basin_uprising,
  conflict_battle_for_imperial_basin,
  conflict_battle_for_spice_refinery,
  conflict_choam_security,
  conflict_cloak_and_dagger,
  conflict_desert_power,
  conflict_grand_vision,
  conflict_guild_bank_raid,
  conflict_machinations,
  conflict_propaganda,
  conflict_protect_the_sietches,
  conflict_raid_stockpiles,
  conflict_secure_imperial_basin_uprising,
  conflict_secure_imperial_basin,
  conflict_seize_spice_refinery,
  conflict_shadow_contest,
  conflict_siege_of_arrakeen_uprising,
  conflict_siege_of_arrakeen,
  conflict_siege_of_carthag,
  conflict_skirmish_1,
  conflict_skirmish_2,
  conflict_skirmish_3,
  conflict_skirmish_4,
  conflict_skirmish_5,
  conflict_skirmish_crysknife,
  conflict_skirmish_desert_mouse,
  conflict_skirmish_ornithopter,
  conflict_sort_through_the_chaos,
  conflict_spice_freighters,
  conflict_storms_in_the_south,
  conflict_terrible_purpose,
  conflict_test_of_loyalty,
  conflict_trade_dispute,
]
