'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const arrakis_observer = require('./arrakis-observer.js')
const bombast = require('./bombast.js')
const choam_demands = require('./choam-demands.js')
const command_center = require('./command-center.js')
const corrupt_bureaucrat = require('./corrupt-bureaucrat.js')
const delivery_logistics = require('./delivery-logistics.js')
const disruption_tactics = require('./disruption-tactics.js')
const eliminate_allies = require('./eliminate-allies.js')
const elite_forces = require('./elite-forces.js')
const engineered_miracle = require('./engineered-miracle.js')
const fremen_war_name = require('./fremen-war-name.js')
const holy_war = require('./holy-war.js')
const i_believe = require('./i-believe.js')
const imperial_throneship = require('./imperial-throneship.js')
const intelligence_training = require('./intelligence-training.js')
const ixian_ambassador = require('./ixian-ambassador.js')
const litany_against_fear = require('./litany-against-fear.js')
const mercantile_affairs = require('./mercantile-affairs.js')
const pointing_the_way = require('./pointing-the-way.js')
const possible_futures = require('./possible-futures.js')
const quash_rebellion = require('./quash-rebellion.js')
const sandwalk = require('./sandwalk.js')
const sardaukar_standard = require('./sardaukar-standard.js')
const shrouded_counsel = require('./shrouded-counsel.js')
const southern_faith = require('./southern-faith.js')
const urgent_shigawire = require('./urgent-shigawire.js')

module.exports = [
  arrakis_observer,
  bombast,
  choam_demands,
  command_center,
  corrupt_bureaucrat,
  delivery_logistics,
  disruption_tactics,
  eliminate_allies,
  elite_forces,
  engineered_miracle,
  fremen_war_name,
  holy_war,
  i_believe,
  imperial_throneship,
  intelligence_training,
  ixian_ambassador,
  litany_against_fear,
  mercantile_affairs,
  pointing_the_way,
  possible_futures,
  quash_rebellion,
  sandwalk,
  sardaukar_standard,
  shrouded_counsel,
  southern_faith,
  urgent_shigawire,
]
