'use strict'

module.exports = {
  id: "shrouded-counsel",
  name: "Shrouded Counsel",
  source: "Bloodlines",
  compatibility: "Uprising",
  count: 1,
  persuasionCost: 4,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [],
  factionAccess: [],
  spyAccess: true,
  agentAbility: "+1 Intrigue card",
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: "If you have 6+ Persuasion:\n· Trash a card",
  factionAffiliation: "bene-gesserit",
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: false,
  hasSpies: true,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
