module.exports =  [
  {
    name: 'FTL Control',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Jump the fleet if the Jump Preparation track is not in the red zone.* *Might lose population',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Weapons Control',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Attack 1 cylon ship with Galactica',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Command',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Activate up to 2 unmanned vipers',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Communications',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Look at the back of 2 civilian ships. You may then move them to adjacent area(s)',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: "Admiral's Quarters",
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a character, then pass this Skill Check to send him to the "Brig"',
    'skill check value': '7',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Research Lab',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Draw 1 engineering or 1 tactics Skill Card',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Hangar Deck',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Launch yourself in a viper. You may then take 1 more action',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Armory',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: false,
    text: 'Action: Attack a centurion on the Boarding Party track (destroyed on roll of 7 - 8)',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Sickbay',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: true,
    text: 'You may only draw 1 Skill Card during your Receive Skills step',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Brig',
    expansion: 'base game',
    area: 'Galactica',
    team: 'human',
    hazardous: true,
    text: 'You may not move, draw Crisis Cards, or add more than 1 card to skill checks. Action: Pass this skill check to move to any location',
    'skill check value': '7',
    politics: true,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Press Room',
    expansion: 'base game',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: Draw 2 politics Skill Cards',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: "President's Office",
    expansion: 'base game',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: If you are President, draw 1 Quorum Card. You may then draw 1 additional Quorum Card or play 1 from your hand',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Administration',
    expansion: 'base game',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a character, then pass this skill check to give him the President title',
    'skill check value': '5',
    politics: true,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Caprica',
    expansion: 'base game',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Play your Super Crisis Card or draw 2 Crisis Cards, choose 1 to resolve and discard the other. * *No Activate Cylon Ships or Prepare for Jump steps',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Cylon Fleet',
    expansion: 'base game',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Activate all Cylon ships of one type, or launch 2 raiders and 1 heavy raider from each basestar',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Human Fleet',
    expansion: 'base game',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: "Action: Look at any player's hand and steal 1 Skill Card (place it in your hand). Then roll a die, and if 5 or higher, damage Galactica",
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Resurrection Ship',
    expansion: 'base game',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: You may discard your Super Crisis Card to draw a new one. Then, if distance is 7 or less, give your unrevealed Loyalty Card(s) to any player',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Pegasus CIC',
    expansion: 'pegasus',
    area: 'Pegasus',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a basestar and roll a die: 1-3: Damage Pegasus. 4-6: Damage basestar. 7-8: Damage basestar twice',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Airlock',
    expansion: 'pegasus',
    area: 'Pegasus',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a character and pass this skill check to execute him. Reduce the difficulty of this skill check by 4 if the character is in the "Brig"',
    'skill check value': '12',
    politics: true,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: true
  },
  {
    name: 'Main Batteries',
    expansion: 'pegasus',
    area: 'Pegasus',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a space area to affect and roll a die: 1: Destroy a civilian ship. 2-3: Damage 1 viper. 4-6: Destroy 2 raiders. 7-8: Destroy 4 raiders',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Engine Room',
    expansion: 'pegasus',
    area: 'Pegasus',
    team: 'human',
    hazardous: false,
    text: 'Action: Discard 2 Skill Cards to treat the next Crisis Card drawn this turn as if it had a "prepare for jump" icon',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Caprica',
    expansion: 'pegasus',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Play 1 of your Super Crisis Card or draw 2 Crisis Cards, choose 1 to resolve and place the other on the bottom of the deck. * *No Activate Cylon Ships step',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Cylon Fleet',
    expansion: 'pegasus',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Activate all Cylon shups of one type, or launch 2 raiders and 1 heavy raider from each basestar',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Human Fleet',
    expansion: 'pegasus',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Look at the top card of the Crisis or Destination deck and place it on the top or bottom of that deck. Then draw 2 Skill Cards of different types (may come from outside your skill set) or Infiltrate Galactica',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Resurrection Ship',
    expansion: 'pegasus',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: true,
    text: 'You may draw only 1 Skill Card during your Receive Skill Cards step. Action: Draw 1 Super Crisis Card',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Medical Center',
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'human',
    hazardous: true,
    text: 'You may only draw 1 Skill Card during your Receive Skills step',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Detention',
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'human',
    hazardous: true,
    text: 'You may not move, or add more than 2 cards to skill checks. Action: Pass this skill check to move to any location',
    'skill check value': '9',
    politics: true,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Resistance HQ',
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'human',
    hazardous: false,
    text: 'Human Action: Choose a character in New Caprica (human or cylon), then pass this skill check to execute him',
    'skill check value': '7',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: true
  },
  {
    name: 'Occupation Authority',
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'both',
    hazardous: false,
    text: 'Human Action: If you are the President, you may draw 1 Quorum Card. Then you may play 1 Quorum Card. Cylon Action: Activate 1 occupation force and then place 1 occupation force on this location',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: "Breeder's Canyon",
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'both',
    hazardous: false,
    text: 'Human Action: Reduce the highest resource by 1 to advance the fleet marker 1 space up the Jump Track. Cylon Action: Draw and resolve the top card of the Crisis deck. Skip the Prepare for Jump step of this turn',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Shipyard',
    expansion: 'pegasus',
    area: 'New Caprica',
    team: 'both',
    hazardous: false,
    text: 'Human Action: Prepare or evacuate 1 civilian ship. If you evacuate a civilian ship, you may then move to any Galactica location. Cylon Action: Look at the top ship of the Locked Civilian Ship stack, and place it on the top or bottom of the stack',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Basestar Bridge',
    expansion: 'cylon fleet board',
    area: 'Cylon Fleet',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Choose 2 of the following abilities. Option 1: The CAG must place 1 civilian ship (following all placement rules). Option 2: Place 1 Basestar or 3 Raiders in any 1 area on this game board. Option 3: Roll a die: 1-3: Decrease the jump track by 1. 4-8: Increase the pursuit track by 1. Option 4: Roll a die. If the result is less than the number of raiders on the main game board, draw 2 Galactica damage tokens and choose 1 to resolve',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Bridge',
    expansion: 'daybreak',
    area: 'Demetrius',
    team: 'human',
    hazardous: false,
    text: 'Action: If there is no Mission Card on the "Active Mission" space, activate the top card of the Mission deck. Do not draw a Crisis Card this turn',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Tactical Plot',
    expansion: 'daybreak',
    area: 'Demetrius',
    team: 'human',
    hazardous: false,
    text: 'Action: Look at the top card of the Mission deck and place it on the top or bottom of the deck',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: "Captain's Cabin",
    expansion: 'daybreak',
    area: 'Demetrius',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose a skill type (it may be from outside your skill set). Each player, including Cylon players, draws 1 Skill Card of that type',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Hybrid Tank',
    expansion: 'daybreak',
    area: 'Rebel Basestar',
    team: 'both',
    hazardous: false,
    text: 'Action: Discard a miracle token or a Super Crisis Card to look at the top 5 cards of the Crisis deck. Then, place them on the top of the deck in the order of your choosing',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Datastream',
    expansion: 'daybreak',
    area: 'Rebel Basestar',
    team: 'both',
    hazardous: false,
    text: 'Action: Discard a miracle token or a Super Crisis Card to search 1 Skill deck and its discard pile for any 3 cards. Then add those cards to your hand and shuffle the discard pile into the deck',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Raider Bay',
    expansion: 'daybreak',
    area: 'Rebel Basestar',
    team: 'both',
    hazardous: false,
    text: 'Action: Discard a miracle token or a Super Crisis Card to choose a space area. Place either 2 raiders or 4 unmanned vipers in this area and immediately activate them',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Quorum Chamber',
    expansion: 'daybreak',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: If you are President, draw 1 Quorum Card. You may then draw 1 additional Quorum Card or play 1 from your hand',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Press Room',
    expansion: 'daybreak',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: Choose another player to draw 1 Mutiny Card. (He does not move to the "Brig"). He keeps 1 of his Mutiny Cards and discards the rest. You may then discard a Mutiny Card',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: "President's Office",
    expansion: 'daybreak',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: Draw 2 politics Skill Cards',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Administration',
    expansion: 'daybreak',
    area: 'Colonial One',
    team: 'human',
    hazardous: false,
    text: 'Action: Draw 1 Mutiny Card. If the President has any Mutiny Cards, choose a player to gain the President title. If the "Accept Prophecy" card is in play, the President may discard it to keep his title',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Caprica',
    expansion: 'daybreak',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Play 1 of your Super Crisis Card or draw 2 Crisis Cards, choose 1 to resolve and place the other on the bottom of the deck. * *No Activate Cylon Ships step',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Cylon Fleet',
    expansion: 'daybreak',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Activate all Cylon shups of one type, or launch 2 raiders and 1 heavy raider from each basestar',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Human Fleet',
    expansion: 'daybreak',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: false,
    text: 'Action: Look at the top card of the Crisis or Destination deck and place it on the top or bottom of that deck. Then draw 2 Skill Card or Action: Infiltrate Galactica',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Resurrection Ship',
    expansion: 'daybreak',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: true,
    text: 'You may draw only 1 Skill Card during your Receive Skill Cards step. Action: Draw 1 Super Crisis Card',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  },
  {
    name: 'Hub Destroyed',
    expansion: 'daybreak',
    area: 'Cylon Locations',
    team: 'cylon',
    hazardous: true,
    text: 'During your Draw Skills step, discard all of your Super Crisis Cards and do not draw Skill Card. Action: Discard 3 Skill Cards to draw 1 Super Crisis Card and move to the "Cylon Fleet" location',
    'skill check value': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false
  }
]
