'use strict'

const contractCards = [
  {
    name: 'Acquire The Spice Must Flow',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Influence with Spacing Guild\n· +3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Arakeen',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Troop\n· +1 Spy',
    riseOfIxSpecific: false,
  },
  {
    name: 'Arakeen',
    source: 'Uprising',
    count: 1,
    reward: '+1 Water',
    riseOfIxSpecific: false,
  },
  {
    name: 'Deliver Supplies',
    source: 'Uprising',
    count: 1,
    reward: '+3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Dreadnought',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Ixian Ambassador\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Espionage',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Solari\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Espionage',
    source: 'Uprising',
    count: 2,
    reward: '+3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Harvest 3+ Spice',
    source: 'Uprising',
    count: 1,
    reward: '+1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Harvest 3+ Spice',
    source: 'Uprising',
    count: 2,
    reward: '+3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Harvest 4+ Spice',
    source: 'Uprising',
    count: 1,
    reward: '· +2 Solari\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Harvest 4+ Spice',
    source: 'Uprising',
    count: 1,
    reward: '+4 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Heighliner',
    source: 'Uprising',
    count: 1,
    reward: '· +3 Solari\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Heighliner',
    source: 'Uprising',
    count: 1,
    reward: '+2 Water',
    riseOfIxSpecific: false,
  },
  {
    name: 'Heighliner',
    source: 'Uprising',
    count: 1,
    reward: '+2 Troops',
    riseOfIxSpecific: false,
  },
  {
    name: 'High Council',
    source: 'Uprising',
    count: 1,
    reward: '+3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'High Council',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Ixian Ambassador\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'High Council',
    source: 'Uprising',
    count: 1,
    reward: '+1 Influence with Bene Gesserit',
    riseOfIxSpecific: false,
  },
  {
    name: 'Immediate',
    source: 'Uprising',
    count: 1,
    reward: '+2 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Interstellar Shipping',
    source: 'Uprising',
    count: 1,
    reward: '· +1 Ixian Ambassador\n· +1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Research Station',
    source: 'Uprising',
    count: 1,
    reward: '+3 Solari',
    riseOfIxSpecific: false,
  },
  {
    name: 'Research Station',
    source: 'Uprising',
    count: 1,
    reward: '· +2 Solari\n· +1 Spy',
    riseOfIxSpecific: false,
  },
  {
    name: 'Sardaukar',
    source: 'Uprising',
    count: 1,
    reward: 'Draw 2 cards',
    riseOfIxSpecific: false,
  },
  {
    name: 'Sardaukar',
    source: 'Uprising',
    count: 1,
    reward: 'Recall an Agent',
    riseOfIxSpecific: false,
  },
  {
    name: 'Secrets',
    source: 'Uprising',
    count: 1,
    reward: '+1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Smuggling',
    source: 'Uprising',
    count: 1,
    reward: '+1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Spice Refinery',
    source: 'Uprising',
    count: 1,
    reward: 'Draw 2 cards',
    riseOfIxSpecific: false,
  },
  {
    name: 'Spice Refinery',
    source: 'Uprising',
    count: 1,
    reward: '+1 Water',
    riseOfIxSpecific: false,
  },
  {
    name: 'Tech Negotiation',
    source: 'Uprising',
    count: 1,
    reward: '+1 Contract',
    riseOfIxSpecific: true,
  },
  {
    name: 'Spice Refinery',
    source: 'Bloodlines',
    count: 1,
    reward: '+2 Troops',
    riseOfIxSpecific: false,
  },
  {
    name: 'High Council',
    source: 'Bloodlines',
    count: 1,
    reward: 'Recall an Agent',
    riseOfIxSpecific: false,
  },
  {
    name: 'Secrets',
    source: 'Bloodlines',
    count: 1,
    reward: '· +2 Solari\n· Draw a card',
    riseOfIxSpecific: false,
  },
  {
    name: 'Earn Any Alliance',
    source: 'Bloodlines',
    count: 1,
    reward: '· +2 Solari\n· +2 Troops',
    riseOfIxSpecific: false,
  },
  {
    name: 'Deliver Supplies',
    source: 'Bloodlines',
    count: 1,
    reward: '· +1 Solari\n· +1 Spy with Deep Cover',
    riseOfIxSpecific: false,
  },
  {
    name: 'Immediate',
    source: 'Bloodlines',
    count: 1,
    reward: 'Trash 1 Intrigue card →\n· +1 Intrigue card\n· Draw a card\n(requires an Intrigue card)',
    riseOfIxSpecific: false,
  },
  {
    name: 'Harvest',
    source: 'Bloodlines',
    count: 1,
    reward: '· +2 Solari\n· +1 Spy',
    riseOfIxSpecific: false,
  },
]

module.exports = contractCards
