'use strict'

const intrigueCards = [
  {
    name: 'Adaptive Tactics',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Spend 1 Spice -> +1 Troop and Combat space.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Advanced Weaponry',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 3 Solari -> +1 Dreadnought',
    combatEffect: 'If you have three or more Tech tiles: +4 Swords',
    endgameEffect: null,
  },
  {
    name: 'Allied Armada',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'If you have a Faction Alliance: Pay 2 Spice --> +7 Swords',
    endgameEffect: null,
  },
  {
    name: 'Ambitious',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Lose three of your troops -> Gain one Influence with a Faction where an oponent has more Influence than you.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Ambush',
    source: 'Base',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+4 Swords',
    endgameEffect: null,
  },
  {
    name: 'Backed by CHOAM',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Lose 1 Influence -> +4 Solari',
    combatEffect: 'If you have completed 2+ Contracts, +4 Swords',
    endgameEffect: null,
  },
  {
    name: 'Battlefield Research',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: 'Retreat 1+ troops -> Buy Tech at a 1 Spice discount',
    endgameEffect: 'If you have three or more Tech tiles: +1 Victory Point',
  },
  {
    name: 'Bindu Suspension',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `At the start of your turn: Draw a card, you may pass your turn
instead of taking an Agent or Reveal turn.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Blackmail',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Lose one Influence -> +5 Swords',
    endgameEffect: null,
  },
  {
    name: 'Breakthrough',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Research',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Bribery',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 2 Solary --> +1 Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Buy Access',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 5 Solari -> +1 Influence in 2 Factions of your choice',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Bypass Protocol',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `Acquire a card that costs 3 Persuation or less. OR
Pay 2 Spice --> Acquire a card that costs 5 Persuation to the top of your deck.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Calculated Hire',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Spice --> Take the Mentat from its designated space in the Landsraad.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Calculating',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'For each type of unit you have in the Conflict: +1 Solari',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Call to Arms',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'During your Reveal turn this round, whenever you acquire a card: +1 Troop',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Cannon Turrets',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords; Each opponent retreats one Dreadnought',
    endgameEffect: null,
  },
  {
    name: 'Change Allegiences',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Lose 1 Influence -> +1 Influence; Pay 3 Spice -> +1 Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Charisma',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Gain 2 Persuation during your Reveal turn this round.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'CHOAM Profits',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: 'If you have completed 4+ Contracts: +1 Victory Point',
  },
  {
    name: 'Choam Shares',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 7 Solari --> +1 Victory point',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Coercive Negotiation',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'When you deploy three or more units to the Conflict in a single turn: Reveal three contracts from the bank. Take one and trash the other two.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Contingency Plan',
    source: 'Uprising',
    compatibility: 'All',
    count: 3,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+2 Solari',
    combatEffect: '+3 Swords',
    endgameEffect: null,
  },
  {
    name: 'Controlled',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Look at the top card of your deck. You may put it back, discard it, or spend 1 Solari to draw it.',
    combatEffect: '+1 Sword',
    endgameEffect: null,
  },
  {
    name: 'Corner The Market',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 2,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: `If you have at least 2 "The Spice Must Flow": +1 Victory point.
If you have more "The Spice Must Flow" than each opponent: +1 Victory point.`,
  },
  {
    name: 'Councilor\'s Ambition',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'If you have a seat on the High Council: +2 Water',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Councilor\'s Dispensation',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'If you have a seat on the High Council: +2 Spice',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Counterattack',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Deploy up to two Troops from your garrison to the Conflict',
    combatEffect: 'If an opponent played a Combat Intrigue card in this Conflict: +4 Swords',
    endgameEffect: null,
  },
  {
    name: 'Crysknife',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: true,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: '+1 Spice',
    combatEffect: null,
    endgameEffect: 'Flip one of your face-up Crysknife or ? Conflict cards -> +1 Victory Point',
  },
  {
    name: 'Cull',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Solari -> Trash a card',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Cunning',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Draw a card OR pay 1 Spice -> Draw a card and Trash a card',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Demand Respect',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: `When you win a Conflict: +1 Influence OR Pay 2 Spice --> +2 Influence
(You may play this card after Resolving Combat.)`,
    endgameEffect: null,
  },
  {
    name: 'Depart for Arrakis',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 2 Spice -> +3 Troops; If you have 3 Influence with the Spacing Guild, Draw a card',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Desert Mouse',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: true,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: '+1 Spice',
    combatEffect: null,
    endgameEffect: 'Flip one of your face-up Desert Mouse or ? Conflict cards -> +1 Victory Point',
  },
  {
    name: 'Desert Support',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Spend 1 Water -> +5 Swords.',
    endgameEffect: null,
  },
  {
    name: 'Detonation',
    source: 'Uprising',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Blow the Shield Wall OR Deploy up to 4 Troops from you garrison to the Conflict',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Devious',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Trash a card from your hand OR Deploy up to 2 troops from your garrison to the Conflict.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Devour',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords; If you have 1+ Sandworm in the Conflict: +2 Swords and Trash a card',
    endgameEffect: null,
  },
  {
    name: 'Discerning',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Discard a card to Draw a card OR If you have an alliance: Draw a card.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Disguised Bureaucrat',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'If 1 DNA, +1 Spice; If 2 DNA, +1 Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Dispatch an Envoy',
    source: 'Base',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `The card you play this turn has the following icons:
Emperor, Spacing Guild, Bene Gesserit and Fremen board spaces.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Distraction',
    source: 'Uprising',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'When you deploy 3+ units to the Conflict in a single turn: +1 Spy. You may place this Spy on the same observation post as another player\'s Spy.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Diversion',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: true,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'When you deploy four or more units to the Conflict in a single turn: Move Freighter once',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Double Cross',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `Pay 1 Solari --> An opponent of your choice loses one troop in the Conflict
and you deploy one troop from your supply to the Conflict.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Economic Positioning',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: 'Retreat two of your Troops -> +3 Solari',
    endgameEffect: 'If you have 10 or more Solari: +1 Victory Point',
  },
  {
    name: 'Emperor\'s Invitation',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Draw a card OR The card you play this turn has the Emperor icon.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Expedite',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: true,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Spice -> Move Freighter once',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'False Orders',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Each opponent spying on the board space where you sent an Agent this turn must move that Spy. Then you place a Spy on that Space.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Favored Subject',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Emperor Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Find Weakness',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords; Recall 1 Spy -> +3 Swords',
    endgameEffect: null,
  },
  {
    name: 'Finesse',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Loose one Influence -> Gain one Influence',
    combatEffect: '+2 Swords',
    endgameEffect: null,
  },
  {
    name: 'Glimpse the Path',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Solari -> +1 Water and Draw a card',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Go to Ground',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Retreat 1 or 2 of your Troops -> +1 Spy',
    endgameEffect: null,
  },
  {
    name: 'Grand Conspiracy',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 2,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: '2 Dreadnoughts, 1+ The Spice Must Flow, 4+ Influence on 2+ Influence tracks, A seat on the High Council; If you have any three: +1 Victory Point; If you have all four: +2 Victory Points',
  },
  {
    name: 'Grasp Arrakis',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: true,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: '+3 Swords',
    endgameEffect: 'Flip two of your face-up Conflict-cards -> +1 Victory Point.',
  },
  {
    name: 'Gruesome Sacrifice',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Lose two of your troops in the Conflict -> +1 Beetle, +2 Specimens',
    endgameEffect: null,
  },
  {
    name: 'Guild Authorization',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Spacing Guild Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Harvest Cells',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'When you lose at least three Troops at the end of a Conflcit: +2 Specimen;. You may also acquire a Tleilaxu card (paying it\'s normal cost)',
    endgameEffect: null,
  },
  {
    name: 'Honor Guard',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: true,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Troop. Recruiting a Sardaukar Commander (including when you acquire one) costs you 1 Solari less this turn.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Illicit Dealings',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Beetle',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Imperium Politics',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Solari -> +1 Influence with Emperor or Spacing Guild',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Impress',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords and Acquire a card that costs 3 Persuasion or less',
    endgameEffect: null,
  },
  {
    name: 'Infiltrate',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Enemy Agents don\'t block your next Agent at board spaces this turn.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Insider Information',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Recall a Spy -> Trash a card and Draw a card OR Ignore Influence requirements on board spaces when sending an Agent this turn.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Insidious',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Give an opponent an Intrigue card from your hand -> +1 Spice. If you gave them a non-Twisted Intrigue card: +1 Spice.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Inspire Awe',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Acquire a card that costs 3 Persuasion or less; if you have one or more Sandworms in the Conflict, put that card in your hand',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Intelligence Report',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Draw a card; If you have 2+ Spies on the board: Draw a card',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Ixian Probe',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Discard two cards -> Draw two cards',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Know Their Ways',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Fremen Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Leverage',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'If you gained Spice this turn: +1 Contract and +1 Solari',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Machine Culture',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: 'Acquire Tech',
    combatEffect: null,
    endgameEffect: 'If you have three or more Tech tiles: +1 Victory Point',
  },
  {
    name: 'Manipulate',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Remove and replace a card in the Imperium Row; during your Reveal turn this round, you may acquire the removed card for 1 less Persuasion',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Market Opportunity',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 2 Solari -> +5 Solari OR pay 5 Solari -> +5 Spice',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Master Tactician',
    source: 'Base',
    compatibility: 'All',
    count: 3,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+3 Swords OR Retreat up to 3 of your troops.',
    endgameEffect: null,
  },
  {
    name: 'Mercenaries',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 3 Solari -> +1 Intrigue card and +2 Troops',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Opportunism',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: 'Lose 1 Influence with 2 Factions of your choice and pay 2 Solari -> +1 Victory Point',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Ornithopter',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: true,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: '+1 Spice',
    combatEffect: null,
    endgameEffect: 'Flip one of your face-up Ornithopter or ? Conflict cards -> +1 Victory Point',
  },
  {
    name: 'Plans Within Plans',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 2,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: `Having 3  Influence (or more) on 3 Factions tracks: +1 Victory point OR
Having 3 Influence (or more) on four Faction tracks: +2 Victory points.`,
  },
  {
    name: 'Poison Snooper',
    source: 'Base',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Look at the top card of your deck, Draw or Trash it.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Private Army',
    source: 'Base',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Pay 2 Spice --> +5 Swords',
    endgameEffect: null,
  },
  {
    name: 'Questionable Methods',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+1 Sword; Lose 1 Influence -> +4 Swords',
    endgameEffect: null,
  },
  {
    name: 'Quid Pro Quo',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 2 Spice -> Gain one Influence with each Faction that has at least one of your Agents on its board spaces',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Rapid Engineering',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: true,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Discard a card -> Buy Tech at a 1 Spice discount OR If you have 3+ Tech tiles, gain an Influence point with two different Factions.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Rapid Mobilization',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Deploy any number of your garrisoned troops to the Conflict.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Reach Agreement',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Retreat 1 or 2 of your Troops -> +1 Contract',
    endgameEffect: null,
  },
  {
    name: 'Recruitment Mission',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `Gain 1 Persuation during your Reveal turn this round.
You may put cards you acquire on top of your deck.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Refocus',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Shuffle your discard pile into your deck, then: Draw 1 card.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Reinforcements',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: `Pay 3 Solari --> +3 Troops, if it's your Reveal turn,
you may deploy any of these troops to the Conflict.`,
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Resourceful',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'The card you play this turn has the following icons: Green, Purple, Yellow.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Return the Favor',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+1 Sword. For each Faction where you have 2+ Influence: +1 Sword.',
    endgameEffect: null,
  },
  {
    name: 'Ripples in the Sand',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+3 Swords. If you have 1+ Sandworm in the Conflict: +1 Intrigue card.',
    endgameEffect: null,
  },
  {
    name: 'Sacred Pools',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: 'Discard a card -> +1 Water',
    combatEffect: null,
    endgameEffect: 'If you have 3+ Water: +1 Victory Point.',
  },
  {
    name: 'Sadistic',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Lose one of your troops -> Draw a card.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Second Wave',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords, Deploy up to two units from your garrison to the Conflcit',
    endgameEffect: null,
  },
  {
    name: 'Secret Forces',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'If you have a seat on the High Council: +2 Troops',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Secret of the Sisterhood',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Bene Gesserit Influence',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Secure Spice Trade',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: 'If you have at least two The Spice Must Flow, +1 Victory Point and +2 Spice',
  },
  {
    name: 'Seize Production',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: true,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+2 Solari OR If you have 1+ Sardaukar Commanders in the Conflict: +2 Spice',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Shaddam\'s Favor',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Troop, and if you have 3 Influence with the Emperor: +3 Solari',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Shadow Alliance',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: null,
    endgameEffect: 'If you have 4+ Influence on a Faction track where an opponent has the Alliance: +1 Victory Point',
  },
  {
    name: 'Shadowy Bargain',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Specimen',
    combatEffect: null,
    endgameEffect: '+1 Beetle',
  },
  {
    name: 'Shrewd',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Lose one of your troops in the Conflict -> +1 Spice.',
    endgameEffect: null,
  },
  {
    name: 'Sietch Ritual',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Discard a card -> +1 Influence with Bene Gesserit or Fremen',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Sinister',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Lose two of your troops -> +1 Intrigue card and +1 Solari.',
    endgameEffect: null,
  },
  {
    name: 'Sleeper Unit',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Solari -> +1 Spy OR Recall a Spy -> +2 Troops',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Special Mission',
    source: 'Uprising',
    compatibility: 'All',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Place 1 Spy on a Purple space OR Recall one Spy -> Blow the Shield Wall and +2 Spice',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Spice is Power',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Retreat 3 of your Troops -> +3 Spice OR Pay 3 Spice -> +6 Swords',
    endgameEffect: null,
  },
  {
    name: 'Spring the Trap',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: 'Recall 2 Spies -> +7 Swords',
    endgameEffect: null,
  },
  {
    name: 'Staged Incident',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: `Lose 3 of your troops in the Conflict --> +1 Victory point.
(If you remove 3 of your troops after playing this card, you gain 1 VP.)`,
    endgameEffect: null,
  },
  {
    name: 'Strategic Push',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords, If you with this Conflict: +2 Solari',
    endgameEffect: null,
  },
  {
    name: 'Strategic Stockpiling',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 2,
    plotEffect: 'Pay 5 Spice -> +1 Victory Point; If you have 3 Influence with the Fremen, pay 3 Water -> +1 Victory Point',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Strongarm',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Loose a Troop -> Gain one Influence with a Faction whose board space you sent an Agent to this turn',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Study Melange',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: '+1 Spice',
    combatEffect: null,
    endgameEffect: 'If you have 3+ Spice and 2 DNA, +1 Victory Point',
  },
  {
    name: 'Tactical Option',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords OR Retreat any number of your Troops',
    endgameEffect: null,
  },
  {
    name: 'Tenuous Bond',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Lose 1 Influence with any Faction -> Gain 1 Influence with any Faction.',
    combatEffect: 'Trash a card from your discard pile that costs 1+ Persuasion -> +4 Swords.',
    endgameEffect: null,
  },
  {
    name: 'The Sleeper Must Awaken',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 4 Spice --> +1 Victory point',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'The Strong Survive',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+3 Troops OR Retreat one of your troops -> Trash a card.',
    endgameEffect: null,
  },
  {
    name: 'Tiebreaker',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords in Combat',
    endgameEffect: '+10 Spice during Endgame\'',
  },
  {
    name: 'Tleilaxu Puppet',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: 'Gain +1 Persuasion during your Reveal turn this round',
    combatEffect: null,
    endgameEffect: 'If you have a seat on the High Council and 2 DNA: +1 Victory Point',
  },
  {
    name: 'To the Victor …',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: `When you win a Conflict: +3 Spice.
(You may play this card after Resolving Combat.)`,
    endgameEffect: null,
  },
  {
    name: 'Unexpected Allies',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 2 Water -> Blow the Shield Wall and +1 Sandworm',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Unnatural',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'Trash an Intrigue card -> +1 Intrigue card. If you trashed a non-Twisted Intrigue card: +1 Troop',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Urgent Mission',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Recal one of your Agents.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Viscious Talents',
    source: 'Immortality',
    compatibility: 'Immortality',
    count: 2,
    hasTech: false,
    hasShipping: false,
    hasResearch: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+2 Swords, with 1 DNA +2 Swords, with two DNA +2 Swords',
    endgameEffect: null,
  },
  {
    name: 'War Chest',
    source: 'Rise of Ix',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 1,
    plotEffect: null,
    combatEffect: 'Pay 2 Solari -> +4 Swords',
    endgameEffect: 'If you have 10 or more Solari: +1 Victory Point',
  },
  {
    name: 'Water of Life',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Pay 1 Water and 1 Spice --> Draw 3 cards',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Water Peddlers Union',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+1 Water',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Weirding Combat',
    source: 'Uprising',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: null,
    combatEffect: '+3 Swords; if 3 Influence with Bene Gesserit, +2 Swords',
    endgameEffect: null,
  },
  {
    name: 'Windfall',
    source: 'Base',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: '+2 Solari',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Withdrawal Agreement',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: false,
    vpsAvailable: 0,
    plotEffect: 'Retreat 3 of your troops -> +1 Influence with any Faction.',
    combatEffect: null,
    endgameEffect: null,
  },
  {
    name: 'Withdrawn',
    source: 'Bloodlines',
    compatibility: 'All',
    count: 1,
    hasTech: false,
    hasShipping: false,
    hasResearch: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    isTwisted: true,
    vpsAvailable: 0,
    plotEffect: 'At the start of yoru turn: Pass your turn.',
    combatEffect: null,
    endgameEffect: null,
  },
]

module.exports = intrigueCards
