'use strict'

const reserveCards = [
  // Base game reserves — NOT used in Uprising
  {
    name: 'Arrakis Liason',
    source: 'Base',
    compatibility: 'Dune Imperium (Base Only)',
    count: 8,
    persuasionCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'purple'],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 2,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'The Spice Must Flow (Base)',
    source: 'Base',
    compatibility: 'Dune Imperium (Base Only)',
    count: 10,
    persuasionCost: 9,
    acquisitionBonus: '+1 Victory Point',
    passiveAbility: null,
    agentIcons: [],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: '+1 Spice',
  },
  {
    name: 'Foldspace',
    source: 'Base',
    compatibility: 'Dune Imperium (Base Only)',
    count: 6,
    persuasionCost: 0,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'purple', 'yellow'],
    factionAccess: ['emperor', 'guild', 'bene-gesserit', 'fremen'],
    agentAbility: null,
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: null,
  },

  // Uprising reserves
  {
    name: 'Prepare the Way',
    source: 'Uprising',
    compatibility: 'Uprising',
    count: 8,
    persuasionCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'purple'],
    factionAccess: [],
    agentAbility: 'With 2 Influence with Bene Gesserit:\n· Draw a card',
    revealPersuasion: 2,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'The Spice Must Flow',
    source: 'Uprising',
    compatibility: 'Uprising',
    count: 10,
    persuasionCost: 9,
    acquisitionBonus: '+1 Victory Point',
    passiveAbility: null,
    agentIcons: [],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: '+1 Spice',
  },
]

module.exports = reserveCards
