'use strict'

const starterCards = [
  {
    name: 'Convincing Argument',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 2,
    agentIcons: [],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 2,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Dagger',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 2,
    agentIcons: ['green'],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 0,
    revealSwords: 1,
    revealAbility: null,
  },
  {
    name: 'Diplomacy',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 1,
    agentIcons: [],
    factionAccess: ['emperor', 'guild', 'bene-gesserit', 'fremen'],
    agentAbility: null,
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Dune, The Desert Planet',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 2,
    agentIcons: ['yellow'],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Reconnaissance',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 1,
    agentIcons: ['purple'],
    factionAccess: [],
    agentAbility: null,
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Seek Allies',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 1,
    agentIcons: [],
    factionAccess: ['emperor', 'guild', 'bene-gesserit', 'fremen'],
    agentAbility: 'Trash this card',
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Signet Ring',
    source: 'Base',
    compatibility: 'All',
    countPerPlayer: 1,
    agentIcons: ['green', 'purple', 'yellow'],
    factionAccess: [],
    agentAbility: 'Signet Ring',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
  },
  {
    name: 'Control the Spice',
    source: 'Rise of Ix',
    compatibility: 'All',
    countPerPlayer: 1,
    agentIcons: ['yellow'],
    factionAccess: [],
    agentAbility: '1 Spice --> Trash a card, +1 Troop',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: '+1 Spice',
  },
  {
    name: 'Experimentation',
    source: 'Immortality',
    compatibility: 'Immortality',
    countPerPlayer: 2,
    agentIcons: [],
    factionAccess: [],
    agentAbility: '+1 Research',
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: '+1 Specimen',
  },
]

module.exports = starterCards
