'use strict'

const techCards = [
  {
    name: 'Troop Transports',
    source: 'Rise of Ix',
    compatibility: 'Shipping (Rise of Ix)',
    spiceCost: 2,
    acquisitionBonus: '+2 Intrigue cards',
    effect: 'Whenever you recruit troops from the Shipping track, recruit an additional troop. You may deploy any of them to the conflict.',
    hasShipping: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Chaumurky',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 4,
    acquisitionBonus: null,
    effect: 'Endgame: You win tiebreakers.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Restricted Ordinance',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 4,
    acquisitionBonus: null,
    effect: 'If you have a seat on the High Council: +4 Swords',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Detonation Devices',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: null,
    effect: 'When you win a Conflict using a dreadnought, you may return a dreadnought to your supply to gain +1 Victory Point instead of taking control of a board space with it.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 9,
  },
  {
    name: 'Holoprojectors',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: null,
    effect: 'Once per round: Discard a card to draw a card.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Invasion Ships',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 5,
    acquisitionBonus: '+4 Troops',
    effect: 'Once per round: Discard a card so that enemy Agents don\'t block your Agent this turn.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Shuttle Fleet',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 6,
    acquisitionBonus: '+1 Influence with any two factions',
    effect: 'Round start: +2 Solari',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Disposal Facility',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: 'You may trash a card',
    effect: 'Reveal turn: If you have 6 Persuasion or more, you may trash one of your cards in play.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Spaceport',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 5,
    acquisitionBonus: 'Draw 2 cards',
    effect: 'You may put cards you acquire on top of your deck.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Windtraps',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: '+1 Water',
    effect: 'When you win a Conflict: +1 Water.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Holtsman Engine',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 6,
    acquisitionBonus: null,
    effect: 'Round start: Draw a card. Endgame: Worth 1 Victory Point if you have at least two The Spice Must Flow.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 1,
  },
  {
    name: 'Artillery',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 1,
    acquisitionBonus: null,
    effect: 'Reveal turn: +1 Sword for each revealed card that provides 1 or more Sword this turn.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Sonic Snoopers',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: '+1 Intrigue card',
    effect: 'Trash this to put any number of your Intrigue cards on the bootom of the Intrigue deck, then draw that many Intrigue cards.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Training Drones',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: null,
    effect: 'Once per round: +1 Troop.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Flagship',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 8,
    acquisitionBonus: '+1 Victory Point',
    effect: 'Once per round: Spend 4 Solari to get +3 Troops.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 1,
  },
  {
    name: 'Minimic Film',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: null,
    effect: 'Reveal turn: +1 Persuasion',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Memocorders',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: '+1 Influence with any faction',
    effect: 'Endgame: If you have 3+ Influence on all four Influence tracks: +1 Victory Point.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 1,
  },
  {
    name: 'Spy Satellites',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    spiceCost: 4,
    acquisitionBonus: null,
    effect: 'Pay 3 Spice to trash this for +1 Victory Point. Endgame: Worth 1 Victory Point for each Faction where you have 1 or less Influence.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 4,
  },
  {
    name: 'Training Depot',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 1,
    acquisitionBonus: null,
    effect: 'Reveal turn: If you have 6+ Persuasion or more, you add two swords to your Combat strength.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Gene-Locked Vault',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: '+1 Intrigue card Draw 1 card',
    effect: 'Your intrigue cards can\'t be stolen unless you have 5+.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Glowglobes',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: '+1 Influence with any faction',
    effect: 'You may look at the top card of your deck at any time.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Planetary Array',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: 'You may trash a card',
    effect: 'When you win a conflict, draw 1 card.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Servo-Receivers',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 2,
    acquisitionBonus: 'Signet Ring ability',
    effect: 'Your Signet Ring has all four faction icons.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Delivery Bay',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: 'Draw 1 card',
    effect: 'Reveal turn: If you have 6+ Persuasion, +2 Solari.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Plasteel Blades',
    source: 'Bloodlines',
    compatibility: 'Bloodlines',
    spiceCost: 3,
    acquisitionBonus: '+4 Solari',
    effect: 'Whenever you recruit a Sardaukar Commander: Trash this -> Gain an additional Sardauker Commander Skill.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: true,
    vpsAvailable: 0,
  },
  {
    name: 'Suspensor Suits',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 3,
    acquisitionBonus: null,
    effect: 'For each Intrigue card you draw or steal during yoru turn: +1 Troop. Deploy it to the Conflict.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Rapid Dropships',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 4,
    acquisitionBonus: '+2 Troops',
    effect: 'Agent turn: Flip to deploy troops.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Self-Destroying Messages',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 4,
    acquisitionBonus: '+2 Intrigue cards',
    effect: 'Reveal turn: +1 Persuasion.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Navigation Chamber',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix',
    spiceCost: 5,
    acquisitionBonus: '+1 Influence with any faction',
    effect: 'Board spaces cost you 1 Spice or 1 Solari less.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Sardaukar High Command',
    source: 'Bloodlines',
    compatibility: 'Bloodlines',
    spiceCost: 7,
    acquisitionBonus: '+1 Victory Point',
    effect: 'Recruiting a Sardaukar Commander (including when you acquire one) costs you 1 Solari less.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: true,
    vpsAvailable: 1,
  },
  {
    name: 'Forbidden Weapons',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 2,
    acquisitionBonus: 'Blow the Shield Wall and +1 Troop',
    effect: 'Reveal turn: You must choose: +3 Swords and -1 Influence with any faction OR Lose all your spice and trash this.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: true,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Advanced Data Analysis',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 3,
    acquisitionBonus: null,
    effect: 'To acquire this, you must trash one of your Spies from the board. Once per round: +1 Intrigue card.',
    hasShipping: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Ornithopter Fleet',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 4,
    acquisitionBonus: '+2 Troops',
    effect: 'All of your battle icons are now Ornithopters.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: true,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Panopticon',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 5,
    acquisitionBonus: null,
    effect: 'Reveal turn: +1 Spy and +1 Troop. Endgame: Gain 1 Influence with each Faction where you have 1 or less Influence.',
    hasShipping: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'Spy Drones',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 5,
    acquisitionBonus: '+2 Spies with Deep Cover',
    effect: 'Once per round: +1 Solari AND If you recalled a Spy this turn: You may trash a card.',
    hasShipping: false,
    hasSpies: true,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 0,
  },
  {
    name: 'CHOAM Transports',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    spiceCost: 6,
    acquisitionBonus: '+1 Contract',
    effect: 'When you complete a contract: Draw a card. Endgame: Worth 1 Victory Point if you have completed for or more contracts.',
    hasShipping: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: true,
    hasBattleIcons: false,
    hasSardaukar: false,
    vpsAvailable: 1,
  },
]

module.exports = techCards
