'use strict'

const tleilaxCards = [
  {
    name: 'Twisted Mentat',
    source: 'Immortality',
    count: 1,
    specimenCost: 4,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'purple'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'You may recall the Agent you sent this turn',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: '+1 Specimen',
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Usurp',
    source: 'Immortality',
    count: 1,
    specimenCost: 4,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: [],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '· You may graft this to a card in the Imperium Row without acquiring it\n· If you do, trash that card at the end of the turn',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: '+1 Specimen',
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Beguiling Pheromones',
    source: 'Immortality',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['purple', 'yellow'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'If you sent an Agent to a Faction board space this turn:\n· Trash one of the grafted cards and gain an additional Influence with that Faction',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Ghola',
    source: 'Immortality',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['purple'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'This card has the same Agent box as the other grafted card',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Scientific Breakthrough',
    source: 'Immortality',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'purple', 'yellow'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '· +1 Research\n· If at 2 DNA: Trash this card → +1 Victory Point',
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 1,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Stitched Horror',
    source: 'Immortality',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['purple'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'Choose two:\n· +1 Water\n· +1 Troop\n· Trash a card\n· +1 Beetle',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Unnatural Reflexes',
    source: 'Immortality',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['yellow'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'If at 1 DNA: Draw 2 cards',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Piter, Genius Advisor',
    source: 'Promo',
    count: 1,
    specimenCost: 3,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green', 'yellow'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'Lose a troop →\n· Draw 2 cards\n· +1 Research',
    revealPersuasion: 1,
    revealSwords: 1,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Face Dancer',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: [],
    factionAccess: ['emperor', 'guild', 'fremen'],
    spyAccess: false,
    agentAbility: 'Draw a card',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: 'emperor',
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'From the Tanks',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '+1 Troops',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Guild Impersonator',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: [],
    factionAccess: ['guild'],
    spyAccess: false,
    agentAbility: 'If you gain spice this turn: +1 Influence with Spacing Guild',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: 'guild',
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Slig Farmer',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '· +1 Solari for each Agent icon on the other grafted card\n· 5 Solari → 1 Beetle',
    revealPersuasion: 0,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Subject X-137',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: '+1 Beetle',
    passiveAbility: null,
    agentIcons: ['green', 'yellow'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'If at 1 DNA, +1 Beetle',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Tleilaxu Infiltrator',
    source: 'Immortality',
    count: 1,
    specimenCost: 2,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['purple'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '· Enemy agents don\'t block your agent this turn\n· Draw a card\n· If at 2 DNA: +1 Intrigue card',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: true,
    hasResearch: true,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Chairdog',
    source: 'Immortality',
    count: 1,
    specimenCost: 1,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['purple'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: 'At the start of your Reveal turn, return the other grafted card from play to your hand',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Contaminator',
    source: 'Immortality',
    count: 1,
    specimenCost: 1,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: [],
    factionAccess: ['fremen'],
    spyAccess: false,
    agentAbility: '+1 Beetle',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: 'fremen',
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Corrino Genes',
    source: 'Immortality',
    count: 1,
    specimenCost: 1,
    acquisitionBonus: '+2 Solari',
    passiveAbility: null,
    agentIcons: [],
    factionAccess: ['emperor'],
    spyAccess: false,
    agentAbility: 'If grafted: +1 Beetle',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: 'emperor',
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: true,
    hasGrafting: false,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Face Dancer Initiate',
    source: 'Immortality',
    count: 1,
    specimenCost: 1,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: [],
    factionAccess: ['emperor', 'guild', 'fremen'],
    spyAccess: false,
    agentAbility: null,
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: 'emperor',
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
  {
    name: 'Industrial Espionage',
    source: 'Immortality',
    count: 1,
    specimenCost: 1,
    acquisitionBonus: null,
    passiveAbility: null,
    agentIcons: ['green'],
    factionAccess: [],
    spyAccess: false,
    agentAbility: '· Draw a card\n· If grafted: +1 Research and +1 Specimen',
    revealPersuasion: 1,
    revealSwords: 0,
    revealAbility: null,
    factionAffiliation: null,
    vpsAvailable: 0,
    hasTech: false,
    hasShipping: false,
    hasUnload: false,
    hasInfiltration: false,
    hasResearch: false,
    hasGrafting: true,
    hasSpies: false,
    hasSandworms: false,
    hasContracts: false,
    hasBattleIcons: false,
    hasSardaukar: false,
  },
]

module.exports = tleilaxCards
