'use strict'

module.exports = {
  id: "assassination-mission",
  name: "Assassination Mission",
  source: "Base",
  compatibility: "All",
  count: 2,
  persuasionCost: 1,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [],
  factionAccess: [],
  spyAccess: false,
  agentAbility: "When trashed by another card or effect:\n· +4 Solari",
  revealPersuasion: 0,
  revealSwords: 1,
  revealAbility: "+1 Solari",
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: false,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
