'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const acquire_the_spice_must_flow = require('./acquire-the-spice-must-flow.js')
const arakeen_1 = require('./arakeen-1.js')
const arakeen_2 = require('./arakeen-2.js')
const deliver_supplies_1 = require('./deliver-supplies-1.js')
const dreadnought = require('./dreadnought.js')
const espionage_1 = require('./espionage-1.js')
const espionage_2 = require('./espionage-2.js')
const harvest_3_spice_1 = require('./harvest-3-spice-1.js')
const harvest_3_spice_2 = require('./harvest-3-spice-2.js')
const harvest_4_spice_1 = require('./harvest-4-spice-1.js')
const harvest_4_spice_2 = require('./harvest-4-spice-2.js')
const heighliner_1 = require('./heighliner-1.js')
const heighliner_2 = require('./heighliner-2.js')
const heighliner_3 = require('./heighliner-3.js')
const high_council_1 = require('./high-council-1.js')
const high_council_2 = require('./high-council-2.js')
const high_council_3 = require('./high-council-3.js')
const immediate_1 = require('./immediate-1.js')
const interstellar_shipping = require('./interstellar-shipping.js')
const research_station_1 = require('./research-station-1.js')
const research_station_2 = require('./research-station-2.js')
const sardaukar_1 = require('./sardaukar-1.js')
const sardaukar_2 = require('./sardaukar-2.js')
const secrets_1 = require('./secrets-1.js')
const smuggling = require('./smuggling.js')
const spice_refinery_1 = require('./spice-refinery-1.js')
const spice_refinery_2 = require('./spice-refinery-2.js')
const tech_negotiation = require('./tech-negotiation.js')
const spice_refinery_3 = require('./spice-refinery-3.js')
const high_council_4 = require('./high-council-4.js')
const secrets_2 = require('./secrets-2.js')
const earn_any_alliance = require('./earn-any-alliance.js')
const deliver_supplies_2 = require('./deliver-supplies-2.js')
const immediate_2 = require('./immediate-2.js')
const harvest = require('./harvest.js')

module.exports = [
  acquire_the_spice_must_flow,
  arakeen_1,
  arakeen_2,
  deliver_supplies_1,
  dreadnought,
  espionage_1,
  espionage_2,
  harvest_3_spice_1,
  harvest_3_spice_2,
  harvest_4_spice_1,
  harvest_4_spice_2,
  heighliner_1,
  heighliner_2,
  heighliner_3,
  high_council_1,
  high_council_2,
  high_council_3,
  immediate_1,
  interstellar_shipping,
  research_station_1,
  research_station_2,
  sardaukar_1,
  sardaukar_2,
  secrets_1,
  smuggling,
  spice_refinery_1,
  spice_refinery_2,
  tech_negotiation,
  spice_refinery_3,
  high_council_4,
  secrets_2,
  earn_any_alliance,
  deliver_supplies_2,
  immediate_2,
  harvest,
]
