/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItemButton']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    DropdownButton: typeof import('./src/components/DropdownButton.vue')['default']
    DropdownDivider: typeof import('./src/components/DropdownDivider.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./src/components/DropdownMenu.vue')['default']
    DropdownRouterLink: typeof import('./src/components/DropdownRouterLink.vue')['default']
    EditableContent: typeof import('./src/components/EditableContent.vue')['default']
    ErrorModal: typeof import('./src/components/ErrorModal.vue')['default']
    GameBase: typeof import('./src/components/GameBase.vue')['default']
    GameHeader: typeof import('./src/components/GameHeader.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    ModalBase: typeof import('./src/components/ModalBase.vue')['default']
    MyGames: typeof import('./src/components/MyGames.vue')['default']
    MyLobbies: typeof import('./src/components/MyLobbies.vue')['default']
    OffCanvas: typeof import('./src/components/OffCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
  }
  export interface GlobalDirectives {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
