'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const arrakis_liason = require('./arrakis-liason.js')
const foldspace = require('./foldspace.js')
const prepare_the_way = require('./prepare-the-way.js')
const the_spice_must_flow_base = require('./the-spice-must-flow-base.js')
const the_spice_must_flow = require('./the-spice-must-flow.js')

module.exports = [
  arrakis_liason,
  foldspace,
  prepare_the_way,
  the_spice_must_flow_base,
  the_spice_must_flow,
]
