'use strict'

module.exports = {
  id: 'chairdog',
  name: 'Chairdog',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 1,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: ['purple'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: 'At the start of your Reveal turn, return the other grafted card from play to your hand',
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: null,
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
