'use strict'

module.exports = {
  id: 'contaminator',
  name: 'Contaminator',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 1,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [],
  factionAccess: ['fremen'],
  spyAccess: false,
  agentAbility: '+1 Beetle',
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: null,
  factionAffiliation: 'fremen',
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: true,
  hasGrafting: false,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
