'use strict'

module.exports = {
  id: 'face-dancer',
  name: 'Face Dancer',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 2,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [],
  factionAccess: ['emperor', 'guild', 'fremen'],
  spyAccess: false,
  agentAbility: 'Draw a card',
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: null,
  factionAffiliation: 'emperor',
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
