'use strict'

module.exports = {
  id: 'ghola',
  name: 'Ghola',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 3,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: ['purple'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: 'This card has the same Agent box as the other grafted card',
  revealPersuasion: 1,
  revealSwords: 1,
  revealAbility: null,
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
