'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const twisted_mentat = require('./twisted-mentat.js')
const usurp = require('./usurp.js')
const beguiling_pheromones = require('./beguiling-pheromones.js')
const ghola = require('./ghola.js')
const scientific_breakthrough = require('./scientific-breakthrough.js')
const stitched_horror = require('./stitched-horror.js')
const unnatural_reflexes = require('./unnatural-reflexes.js')
const piter_genius_advisor = require('./piter-genius-advisor.js')
const face_dancer = require('./face-dancer.js')
const from_the_tanks = require('./from-the-tanks.js')
const guild_impersonator = require('./guild-impersonator.js')
const slig_farmer = require('./slig-farmer.js')
const subject_x_137 = require('./subject-x-137.js')
const tleilaxu_infiltrator = require('./tleilaxu-infiltrator.js')
const chairdog = require('./chairdog.js')
const contaminator = require('./contaminator.js')
const corrino_genes = require('./corrino-genes.js')
const face_dancer_initiate = require('./face-dancer-initiate.js')
const industrial_espionage = require('./industrial-espionage.js')

module.exports = [
  twisted_mentat,
  usurp,
  beguiling_pheromones,
  ghola,
  scientific_breakthrough,
  stitched_horror,
  unnatural_reflexes,
  piter_genius_advisor,
  face_dancer,
  from_the_tanks,
  guild_impersonator,
  slig_farmer,
  subject_x_137,
  tleilaxu_infiltrator,
  chairdog,
  contaminator,
  corrino_genes,
  face_dancer_initiate,
  industrial_espionage,
]
