'use strict'

module.exports = {
  id: 'slig-farmer',
  name: 'Slig Farmer',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 2,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: ['green'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: '· +1 Solari for each Agent icon on the other grafted card\n· 5 Solari → 1 Beetle',
  revealPersuasion: 0,
  revealSwords: 0,
  revealAbility: null,
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: true,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
