'use strict'

module.exports = {
  id: 'stitched-horror',
  name: 'Stitched Horror',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 3,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: ['purple'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: 'Choose two:\n· +1 Water\n· +1 Troop\n· Trash a card\n· +1 Beetle',
  revealPersuasion: 1,
  revealSwords: 1,
  revealAbility: null,
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: true,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
