'use strict'

module.exports = {
  id: 'subject-x-137',
  name: 'Subject X-137',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 2,
  acquisitionBonus: '+1 Beetle',
  passiveAbility: null,
  agentIcons: ['green', 'yellow'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: 'If at 1 DNA, +1 Beetle',
  revealPersuasion: 1,
  revealSwords: 0,
  revealAbility: null,
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: true,
  hasGrafting: false,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
