'use strict'

module.exports = {
  id: 'twisted-mentat',
  name: 'Twisted Mentat',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 4,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: ['green', 'purple'],
  factionAccess: [],
  spyAccess: false,
  agentAbility: 'You may recall the Agent you sent this turn',
  revealPersuasion: 1,
  revealSwords: 1,
  revealAbility: '+1 Specimen',
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
