'use strict'

module.exports = {
  id: 'usurp',
  name: 'Usurp',
  source: 'Immortality',
  compatibility: 'All',
  count: 1,
  specimenCost: 4,
  acquisitionBonus: null,
  passiveAbility: null,
  agentIcons: [],
  factionAccess: [],
  spyAccess: false,
  agentAbility: '· You may graft this to a card in the Imperium Row without acquiring it\n· If you do, trash that card at the end of the turn',
  revealPersuasion: 1,
  revealSwords: 1,
  revealAbility: '+1 Specimen',
  factionAffiliation: null,
  vpsAvailable: 0,
  hasTech: false,
  hasShipping: false,
  hasUnload: false,
  hasInfiltration: false,
  hasResearch: false,
  hasGrafting: true,
  hasSpies: false,
  hasSandworms: false,
  hasContracts: false,
  hasBattleIcons: false,
  hasSardaukar: false,
}
