#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const commonDir = path.resolve(__dirname, '..')
const distDir = path.resolve(commonDir, '..', 'common_dist')

// Ensure dist directory exists
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true })
}

// Function to copy a file
function copyFile(src, dest) {
  const destDir = path.dirname(dest)
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true })
  }
  fs.copyFileSync(src, dest)
}

// Function to copy a directory recursively, excluding certain patterns
function copyDirectory(src, dest, excludePatterns = []) {
  if (!fs.existsSync(src)) {
    return
  }

  const entries = fs.readdirSync(src, { withFileTypes: true })

  for (const entry of entries) {
    const srcPath = path.join(src, entry.name)
    const destPath = path.join(dest, entry.name)

    // Skip if matches exclude pattern
    if (excludePatterns.some(pattern => {
      if (typeof pattern === 'string') {
        return entry.name === pattern || srcPath.includes(pattern)
      }
      if (pattern instanceof RegExp) {
        return pattern.test(entry.name) || pattern.test(srcPath)
      }
      return false
    })) {
      continue
    }

    if (entry.isDirectory()) {
      if (!fs.existsSync(destPath)) {
        fs.mkdirSync(destPath, { recursive: true })
      }
      copyDirectory(srcPath, destPath, excludePatterns)
    }
    else if (entry.isFile()) {
      // Skip TypeScript source files (they'll be compiled)
      // But keep .d.ts files and test files
      if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts') && !entry.name.endsWith('.test.ts')) {
        continue
      }
      // Skip source maps (they'll be generated by TypeScript)
      if (entry.name.endsWith('.js.map') || entry.name.endsWith('.d.ts.map')) {
        continue
      }
      copyFile(srcPath, destPath)
    }
  }
}

// Patterns to exclude
const excludePatterns = [
  'node_modules',
  '.git',
  'coverage',
  'scripts', // Don't copy build scripts
  'tsconfig.json',
  '.eslintrc*',
  'eslint.config.js',
]

// Copy all files and directories except excluded ones
console.log('Copying files from common to common_dist...')

// Copy root-level files
const rootFiles = fs.readdirSync(commonDir, { withFileTypes: true })
for (const entry of rootFiles) {
  if (entry.isFile()) {
    const fileName = entry.name
    // Skip certain files
    if (fileName === 'package-lock.json' ||
        fileName === 'tsconfig.json' ||
        (fileName.startsWith('.') && fileName !== '.babelrc') ||
        fileName.endsWith('.ts')) {
      continue
    }
    // Copy package.json but we'll modify it
    if (fileName === 'package.json') {
      const packageJson = JSON.parse(fs.readFileSync(path.join(commonDir, fileName), 'utf8'))
      // Update main to point to the dist location
      packageJson.main = 'main.js'
      fs.writeFileSync(path.join(distDir, fileName), JSON.stringify(packageJson, null, 2) + '\n')
    }
    else {
      copyFile(path.join(commonDir, fileName), path.join(distDir, fileName))
    }
  }
  else if (entry.isDirectory() && entry.name !== 'node_modules' && entry.name !== 'scripts') {
    copyDirectory(
      path.join(commonDir, entry.name),
      path.join(distDir, entry.name),
      excludePatterns
    )
  }
}

// Explicitly copy .babelrc if it exists
const babelrcPath = path.join(commonDir, '.babelrc')
if (fs.existsSync(babelrcPath)) {
  copyFile(babelrcPath, path.join(distDir, '.babelrc'))
}

console.log('Build complete! Files copied to common_dist')
console.log('Installing dependencies in common_dist...')

// Run npm install in common_dist
const { execSync } = require('child_process')
try {
  execSync('npm install', {
    cwd: distDir,
    stdio: 'inherit',
    env: { ...process.env, npm_config_progress: 'false' }
  })
  console.log('Dependencies installed successfully')
}
catch {
  console.error('Warning: Failed to install dependencies in common_dist')
  console.error('You may need to run "npm install" manually in common_dist')
}

