'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const advanced_data_analysis = require('./advanced-data-analysis.js')
const artillery = require('./artillery.js')
const chaumurky = require('./chaumurky.js')
const choam_transports = require('./choam-transports.js')
const delivery_bay = require('./delivery-bay.js')
const detonation_devices = require('./detonation-devices.js')
const disposal_facility = require('./disposal-facility.js')
const flagship = require('./flagship.js')
const forbidden_weapons = require('./forbidden-weapons.js')
const gene_locked_vault = require('./gene-locked-vault.js')
const glowglobes = require('./glowglobes.js')
const holoprojectors = require('./holoprojectors.js')
const holtsman_engine = require('./holtsman-engine.js')
const invasion_ships = require('./invasion-ships.js')
const memocorders = require('./memocorders.js')
const minimic_film = require('./minimic-film.js')
const navigation_chamber = require('./navigation-chamber.js')
const ornithopter_fleet = require('./ornithopter-fleet.js')
const panopticon = require('./panopticon.js')
const planetary_array = require('./planetary-array.js')
const plasteel_blades = require('./plasteel-blades.js')
const rapid_dropships = require('./rapid-dropships.js')
const restricted_ordinance = require('./restricted-ordinance.js')
const sardaukar_high_command = require('./sardaukar-high-command.js')
const self_destroying_messages = require('./self-destroying-messages.js')
const servo_receivers = require('./servo-receivers.js')
const shuttle_fleet = require('./shuttle-fleet.js')
const sonic_snoopers = require('./sonic-snoopers.js')
const spaceport = require('./spaceport.js')
const spy_drones = require('./spy-drones.js')
const spy_satellites = require('./spy-satellites.js')
const suspensor_suits = require('./suspensor-suits.js')
const training_depot = require('./training-depot.js')
const training_drones = require('./training-drones.js')
const troop_transports = require('./troop-transports.js')
const windtraps = require('./windtraps.js')

module.exports = [
  advanced_data_analysis,
  artillery,
  chaumurky,
  choam_transports,
  delivery_bay,
  detonation_devices,
  disposal_facility,
  flagship,
  forbidden_weapons,
  gene_locked_vault,
  glowglobes,
  holoprojectors,
  holtsman_engine,
  invasion_ships,
  memocorders,
  minimic_film,
  navigation_chamber,
  ornithopter_fleet,
  panopticon,
  planetary_array,
  plasteel_blades,
  rapid_dropships,
  restricted_ordinance,
  sardaukar_high_command,
  self_destroying_messages,
  servo_receivers,
  shuttle_fleet,
  sonic_snoopers,
  spaceport,
  spy_drones,
  spy_satellites,
  suspensor_suits,
  training_depot,
  training_drones,
  troop_transports,
  windtraps,
]
