'use strict'

const leaderData = [
  {
    name: 'Duke Leto Atreides',
    source: 'Base',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Landsraad Popularity: Sending an Agent to a Green board space costs you 1 Solari less.',
    signetRingAbility: 'Prudent Diplomacy: Pay 1 Spice: Gain 1 Influence with a Faction where an opponent has more than you.',
    complexity: 2,
  },
  {
    name: 'Paul Atreides',
    source: 'Base',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Prescience: You may look at the top card of your deck at any time.',
    signetRingAbility: 'Discipline: Draw 1 card.',
    complexity: 1,
  },
  {
    name: 'Muad\'Dib',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Unpredictable Foe: Reveal Turn: If you have one or more sandworms in the Conflict: +1 Intrigue',
    signetRingAbility: 'Lead the Way: +1 Draw',
    complexity: 1,
  },
  {
    name: 'Gurney Halleck',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Always Smiling: If you have 6 or more strength in the Conflict (10 in a six-player game): +1 Persuasion',
    signetRingAbility: 'Warmaster: +1 Troop',
    complexity: 1,
  },
  {
    name: 'Lady Jessica',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Other Memories: When you send an Agent to a Bene Gesserit board space, you may return all your memories to your supply, drawing a card for each one. Then flip this Leader over.',
    signetRingAbility: 'Spice Agony: Trade 1 Spice for 1 Intrigue card and move a troop from your supply to the Bene Gesserit area of the board. It is now a memory.',
    complexity: 2,
  },
  {
    name: 'Shaddam Corrino IV',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Corrino',
    startingEffect: null,
    leaderAbility: 'Sardaukar Commander: Set aside both Sardaukar contracts. Only you can acquire them during the game.',
    signetRingAbility: 'Emperor of the Known Universe: Units can\'t be deployed to the Conflict this turn. +1 Solari and +1 Troop OR trade 3 Solari for +1 Influence',
    complexity: 2,
  },
  {
    name: 'Princess Irulan',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Corrino',
    startingEffect: null,
    leaderAbility: 'Imperial Birthright: When you reach 2 Influence with the Emperor: +1 Intrigue',
    signetRingAbility: 'Chronicler\'s Insight: You may choose: Acquire a card that costs 1 Persuasion OR trash a card from your hand. If it has a cost of 1+ Persuasion: +2 Spice',
    complexity: 2,
  },
  {
    name: 'Archduke Armand Ecaz',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Ecaz',
    startingEffect: null,
    leaderAbility: `Coordination: At reveal turn:
You may trash one of your cards In Play.`,
    signetRingAbility: `Conscript: You may acquire a card
that costs 3 Persuation or les.`,
    complexity: 2,
  },
  {
    name: 'Ilesa Ecaz',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Ecaz',
    startingEffect: null,
    leaderAbility: 'One Step Ahead: Round start: Set aside a card. If you use it to send an Agent: Gain Spice or Solari.',
    signetRingAbility: 'Guild Contacts: Pay 1 Solari: Gain 1 Foldspace card.',
    complexity: 3,
  },
  {
    name: 'Lady Margot Fenring',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Fenring',
    startingEffect: null,
    leaderAbility: 'Loyalty: When you reach 2 Influence with the the Bene Gesserit, +2 Spice.',
    signetRingAbility: 'Arrakis Informant: +1 Spy on any purple space.',
    complexity: 1,
  },
  {
    name: 'Baron Vladimir Harkonnen',
    source: 'Base',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: `Masterstroke: Once per game:
Gain +1 Influence to 2 Factions.`,
    signetRingAbility: 'Scheme: Pay 1 Solari: Draw 1 Intrigue card.',
    complexity: 3,
  },
  {
    name: 'Glossu “The Beast” Rabban',
    source: 'Base',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: 'Arrakis Fiefdom: At game start: +1 Spice and +1 Solari.',
    signetRingAbility: `Brutality: +1 Troop or +2 Troops
if you have at least 1 Faction Alliance.`,
    complexity: 1,
  },
  {
    name: 'Feyd-Rautha Harkonnen',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: 'Devious Strength: Reveal Turn: Recall a Spy for 2 Strength.',
    signetRingAbility: 'Personal Training: Move your Feyd token one space to the right on your Training track, earning the reward on the new space.',
    complexity: 1,
  },
  {
    name: 'Lady Amber Metulli',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Metulli',
    startingEffect: null,
    leaderAbility: 'Desert Scouts: Reveal Turn: You may retreat one of your troops.',
    signetRingAbility: 'Fill Coffers: +1 Solari and if you have an Alliance: +1 Spice',
    complexity: 1,
  },
  {
    name: 'Princess Yuna Moritani',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Moritani',
    startingEffect: null,
    leaderAbility: 'Smuggling Operation: At game start: no Water. When you gain Solari on your turn, gain +1 Solari.',
    signetRingAbility: `Final Delivery: Pay 7 Solari:
Gain +1 Influence, +1 Troop, +1 Spice`,
    complexity: 2,
  },
  {
    name: 'Viscount Hundro Moritani',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    house: 'Moritani',
    startingEffect: null,
    leaderAbility: 'Intelligence: At game start: Look at the top 2 cards of the Intrigue deck. Keep 1, put the other back on top.',
    signetRingAbility: 'Couriers: Pay 1 Spice: +1 Dreadnought',
    complexity: 1,
  },
  {
    name: 'Helena Richese',
    source: 'Base',
    compatibility: 'All',
    house: 'Richese',
    startingEffect: null,
    leaderAbility: 'Eyes Everywhere: Enemy Agents don\'t block your Agents at Green or Blue board spaces.',
    signetRingAbility: 'Manipulate: Remove a card in the Imperium Row. You may acquire this  card for 1 Persuation less.',
    complexity: 2,
  },
  {
    name: 'Count Ilban Richese',
    source: 'Base',
    compatibility: 'All',
    house: 'Richese',
    startingEffect: null,
    leaderAbility: 'Ruthless Negotiator: When you pay Solari for the cost of a board Space: Draw 1 card.',
    signetRingAbility: 'Manufacturing: +1 Solari',
    complexity: 1,
  },
  {
    name: 'Countess Ariana Thorvald',
    source: 'Base',
    compatibility: 'All',
    house: 'Thorvald',
    startingEffect: null,
    leaderAbility: `Spice Addict: When you harvest spice:
gain 1 less spice and draw 1 card.`,
    signetRingAbility: 'Hidden Reservoir: +1 Water',
    complexity: 3,
  },
  {
    name: 'Earl Memnon Thorvald',
    source: 'Base',
    compatibility: 'All',
    house: 'Thorvald',
    startingEffect: null,
    leaderAbility: 'Connections: When you take a High Counsil seat: Gain +1 Influence.',
    signetRingAbility: 'Spice Hoard: +1 Spice.',
    complexity: 1,
  },
  {
    name: 'Tessia Vernius',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Vernius',
    startingEffect: null,
    leaderAbility: 'Careful Observation: Use Snooper tokens on the Influence track to gain rewards.',
    signetRingAbility: 'Duplicity: Lose 1 Influence: Gain 1 Influence with a Faction where you have a Snooper token.',
    complexity: 4,
  },
  {
    name: 'Prince Rhombur Vernius',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    house: 'Vernius',
    startingEffect: null,
    leaderAbility: 'Heavy Lasgun Cannons: Your dreadnoughts have 4 Swords (instead of 3).',
    signetRingAbility: 'Ixian Technology: Acquire Tech or Tech Negotiation.',
    complexity: 1,
  },
  {
    name: 'Staban Tuek',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: null,
    startingEffect: 'Limited Allies: You start the game without Diplomacy in your deck.',
    leaderAbility: 'Smuggle Spice: Whenever another player sends an Agent to a Maker board space you are spying on: +1 Spice.',
    signetRingAbility: 'Unseen Network: +1 Spy. If placed on green, you may trade 1 Spice for 3 Solari. If placed on a Faction space, you may trade 2 Solari for 1 Intrigue card.',
    complexity: 3,
  },
  {
    name: 'Duncan Idaho',
    source: 'Bloodlines',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Ginaz Swordmaster: The Swordmaster boardspace costs you 2 Solari less.',
    signetRingAbility: 'Into the Fray: You may take an Agent you sent this turn and deploy it to the Conflict as a 2 strength unit that can\'t be retreated. If you have your Swordmaster, it has 3 strength instead.',
    complexity: 1,
  },
  {
    name: 'Chani',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: null,
    leaderAbility: 'Tactician: Whenever you retreat or lose any number of troops from the Conflict, advance your Tactics token that many spaces, earning rewards as you reach them. Reset the token after reaching the end of the track.',
    signetRingAbility: 'Fedaykin Maneuver: Retreat any number of your troops OR If you have 2+ Influnece with the Fremen, trade 1 Water for 2 card Draws.',
    complexity: 2,
  },
  {
    name: 'Piter de Vries',
    source: 'Bloodlines',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: 'Twisted Genius: Shuffle the Twisted Intrigue deck and place it face down near you.',
    leaderAbility: 'Twisted Genius: Round Start: Draw a Twisted Intrigue card. (These count as Intrigue cards and can be stolen)',
    signetRingAbility: 'Harkonnen Advisor: +1 Troop. You can\'t deploy this troop to the Conflict this turn.',
    complexity: 2,
  },
  {
    name: 'Esmar Tuek',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: null,
    leaderAbility: 'Tuek\'s Sietch: Whenever you send an Agent to Tuek\'s Sietch: +1 Solari. Whenever an opponent sends an Agent there: +1 Intrigue.',
    signetRingAbility: 'Smuggle Spice: Place 1 bonus spice on Tuek\'s Sietch OR Take 1 bonus spice from a Maker board space.',
    complexity: 1,
  },
  {
    name: 'Steersman Y\'rkoon',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: `Strange Form: You start the game with no Water and no Signet Ring in your deck. 

Plot Course: Shuffle the Navigation cards and draw a hand of five. Choose four to place face down above, in order. Return all others to the box. Whenever you reach 2 Influence with a Faction, play the next Navigation card above (starting from the left).`,
    leaderAbility: 'Hungry for Spice: Whenever you gain 3+ spice in a single turn, Draw 1 card.',
    signetRingAbility: null,
    complexity: 3,
  },
  {
    name: 'Count Hasimir Fenring',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: 'Fenring',
    startingEffect: null,
    leaderAbility: 'Assassin: Whenever you trash a card: +1 Solari.',
    signetRingAbility: 'Corrino Liason: You may trash a card in your play area OR Place 1 Spy with Deep Cover on the Emperor board area.',
    complexity: 2,
  },
  {
    name: 'Gaius Helen Mohiam',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: null,
    startingEffect: null,
    leaderAbility: 'Clandestine: Each card you play has the Spy icon. Whenever you could recall a Spy to Gather Intelligence, you must.',
    signetRingAbility: 'Listeners: Place 1 Spy on a Green space OR Pay 1 Spice -> +1 Spy.',
    complexity: 3,
  },
  {
    name: 'Liet Kynes',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: null,
    startingEffect: null,
    leaderAbility: 'Arrakis Planetologist: Ignore the Influence requirement of Sietch Tabr. You summon no sandworms. For each one you would, instead: Trash 1 card, +1 Spice, +1 Intrigue (even when the Conflict is protected by the Shield Wall).',
    signetRingAbility: 'Judge of the Change: If you sent an Agent this turn to: Green board space AND 2+ Influence with the Emperor -> +1 Water; Purple board space -> +1 Solari; Yellow board space: +1 Spice.',
    complexity: 3,
  },
  {
    name: 'Kota Odax of Ix',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix OR Bloodlines',
    house: null,
    startingEffect: 'Secret Project: Peek at the bottom Tech tile of each stack. Place one face down here.',
    leaderAbility: 'Secret Project: Whenever you could acquire a Tech tile, you may choose the one you set aside. It costs 1 Spice less.',
    signetRingAbility: 'Reverse Engineering: +1 Spice OR Trash one of your Tech tiles -> +1 Intrigue and Draw 1 card.',
    complexity: 3,
  },
]

module.exports = leaderData
