'use strict'

const leaderData = [
  {
    name: 'Duke Leto Atreides',
    source: 'Base',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Landsraad Popularity\nSending an Agent to a Green board space costs you 1 Solari less.',
    signetRingAbility: 'Prudent Diplomacy\nPay 1 Spice:\n· +1 Influence with a Faction where an opponent has more than you',
    complexity: 2,
  },
  {
    name: 'Paul Atreides',
    source: 'Base',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Prescience\nYou may look at the top card of your deck at any time.',
    signetRingAbility: 'Discipline\n· Draw 1 card',
    complexity: 1,
  },
  {
    name: 'Muad\'Dib',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Unpredictable Foe\nReveal Turn: If you have 1+ sandworms in the Conflict:\n· +1 Intrigue',
    signetRingAbility: 'Lead the Way\n· +1 Draw',
    complexity: 1,
  },
  {
    name: 'Gurney Halleck',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Always Smiling\nIf you have 6+ strength in the Conflict (10 in a six-player game):\n· +1 Persuasion',
    signetRingAbility: 'Warmaster\n· +1 Troop',
    complexity: 1,
  },
  {
    name: 'Lady Jessica',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Other Memories\nWhen you send an Agent to a Bene Gesserit board space:\n· Return all your memories to your supply\n· Draw a card for each one\n· Flip this Leader over',
    signetRingAbility: 'Spice Agony\nPay 1 Spice:\n· +1 Intrigue card\n· Move a troop from your supply to the BG area (becomes a memory)',
    complexity: 2,
  },
  {
    name: 'Shaddam Corrino IV',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Corrino',
    startingEffect: null,
    leaderAbility: 'Sardaukar Commander\nSet aside both Sardaukar contracts. Only you can acquire them.',
    signetRingAbility: 'Emperor of the Known Universe\nUnits can\'t be deployed to the Conflict this turn.\n· +1 Solari and +1 Troop\n  OR\n· Pay 3 Solari → +1 Influence',
    complexity: 2,
  },
  {
    name: 'Princess Irulan',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Corrino',
    startingEffect: null,
    leaderAbility: 'Imperial Birthright\nWhen you reach 2 Influence with the Emperor:\n· +1 Intrigue',
    signetRingAbility: 'Chronicler\'s Insight\nChoose one:\n· Acquire a card that costs 1 Persuasion\n· Trash a card from your hand. If it costs 1+ Persuasion: +2 Spice',
    complexity: 2,
  },
  {
    name: 'Archduke Armand Ecaz',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Ecaz',
    startingEffect: null,
    leaderAbility: 'Coordination\nReveal Turn:\n· You may trash one of your cards In Play',
    signetRingAbility: 'Conscript\n· Acquire a card that costs 3 Persuasion or less',
    complexity: 2,
  },
  {
    name: 'Ilesa Ecaz',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Ecaz',
    startingEffect: null,
    leaderAbility: 'One Step Ahead\nRound Start:\n· Set aside a card\n· If you use it to send an Agent: +1 Spice or +1 Solari',
    signetRingAbility: 'Guild Contacts\nPay 1 Solari:\n· +1 Foldspace card',
    complexity: 3,
  },
  {
    name: 'Lady Margot Fenring',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Fenring',
    startingEffect: null,
    leaderAbility: 'Loyalty\nWhen you reach 2 Influence with the Bene Gesserit:\n· +2 Spice',
    signetRingAbility: 'Arrakis Informant\n· +1 Spy on any purple space',
    complexity: 1,
  },
  {
    name: 'Baron Vladimir Harkonnen',
    source: 'Base',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: 'Masterstroke\nOnce per game:\n· +1 Influence to 2 Factions',
    signetRingAbility: 'Scheme\nPay 1 Solari:\n· Draw 1 Intrigue card',
    complexity: 3,
  },
  {
    name: 'Glossu \u201CThe Beast\u201D Rabban',
    source: 'Base',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: 'Arrakis Fiefdom\nAt game start:\n· +1 Spice\n· +1 Solari',
    signetRingAbility: 'Brutality\n· +1 Troop\n· +2 Troops if you have at least 1 Faction Alliance',
    complexity: 1,
  },
  {
    name: 'Feyd-Rautha Harkonnen',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: 'Harkonnen',
    startingEffect: null,
    leaderAbility: 'Devious Strength\nReveal Turn:\n· Recall a Spy for 2 Strength',
    signetRingAbility: 'Personal Training\nMove your Feyd token one space to the right on your Training track, earning the reward on the new space.',
    complexity: 1,
  },
  {
    name: 'Lady Amber Metulli',
    source: 'Uprising',
    compatibility: 'All',
    house: 'Metulli',
    startingEffect: null,
    leaderAbility: 'Desert Scouts\nReveal Turn:\n· You may retreat one of your troops',
    signetRingAbility: 'Fill Coffers\n· +1 Solari\n· If you have an Alliance: +1 Spice',
    complexity: 1,
  },
  {
    name: 'Princess Yuna Moritani',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Moritani',
    startingEffect: null,
    leaderAbility: 'Smuggling Operation\nAt game start: no Water.\nWhen you gain Solari on your turn:\n· +1 Solari',
    signetRingAbility: 'Final Delivery\nPay 7 Solari:\n· +1 Influence\n· +1 Troop\n· +1 Spice',
    complexity: 2,
  },
  {
    name: 'Viscount Hundro Moritani',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    house: 'Moritani',
    startingEffect: null,
    leaderAbility: 'Intelligence\nAt game start:\n· Look at the top 2 cards of the Intrigue deck\n· Keep 1, put the other back on top',
    signetRingAbility: 'Couriers\nPay 1 Spice:\n· +1 Dreadnought',
    complexity: 1,
  },
  {
    name: 'Helena Richese',
    source: 'Base',
    compatibility: 'All',
    house: 'Richese',
    startingEffect: null,
    leaderAbility: 'Eyes Everywhere\nEnemy Agents don\'t block your Agents at Green or Blue board spaces.',
    signetRingAbility: 'Manipulate\n· Remove a card in the Imperium Row\n· You may acquire it for 1 Persuasion less',
    complexity: 2,
  },
  {
    name: 'Count Ilban Richese',
    source: 'Base',
    compatibility: 'All',
    house: 'Richese',
    startingEffect: null,
    leaderAbility: 'Ruthless Negotiator\nWhen you pay Solari for the cost of a board space:\n· Draw 1 card',
    signetRingAbility: 'Manufacturing\n· +1 Solari',
    complexity: 1,
  },
  {
    name: 'Countess Ariana Thorvald',
    source: 'Base',
    compatibility: 'All',
    house: 'Thorvald',
    startingEffect: null,
    leaderAbility: 'Spice Addict\nWhen you harvest spice:\n· Gain 1 less spice\n· Draw 1 card',
    signetRingAbility: 'Hidden Reservoir\n· +1 Water',
    complexity: 3,
  },
  {
    name: 'Earl Memnon Thorvald',
    source: 'Base',
    compatibility: 'All',
    house: 'Thorvald',
    startingEffect: null,
    leaderAbility: 'Connections\nWhen you take a High Council seat:\n· +1 Influence',
    signetRingAbility: 'Spice Hoard\n· +1 Spice',
    complexity: 1,
  },
  {
    name: 'Tessia Vernius',
    source: 'Rise of Ix',
    compatibility: 'All',
    house: 'Vernius',
    startingEffect: null,
    leaderAbility: 'Careful Observation\nUse Snooper tokens on the Influence track to gain rewards.',
    signetRingAbility: 'Duplicity\nLose 1 Influence:\n· +1 Influence with a Faction where you have a Snooper token',
    complexity: 4,
  },
  {
    name: 'Prince Rhombur Vernius',
    source: 'Rise of Ix',
    compatibility: 'Rise of Ix',
    house: 'Vernius',
    startingEffect: null,
    leaderAbility: 'Heavy Lasgun Cannons\nYour dreadnoughts have 4 Swords (instead of 3).',
    signetRingAbility: 'Ixian Technology\n· Acquire Tech or Tech Negotiation',
    complexity: 1,
  },
  {
    name: 'Staban Tuek',
    source: 'Uprising',
    compatibility: 'Uprising',
    house: null,
    startingEffect: 'Limited Allies\nYou start the game without Diplomacy in your deck.',
    leaderAbility: 'Smuggle Spice\nWhenever another player sends an Agent to a Maker board space you are spying on:\n· +1 Spice',
    signetRingAbility: 'Unseen Network\n· +1 Spy\nIf placed on Green:\n· Trade 1 Spice for 3 Solari\nIf placed on a Faction space:\n· Trade 2 Solari for 1 Intrigue card',
    complexity: 3,
  },
  {
    name: 'Duncan Idaho',
    source: 'Bloodlines',
    compatibility: 'All',
    house: 'Atreides',
    startingEffect: null,
    leaderAbility: 'Ginaz Swordmaster\nThe Swordmaster board space costs you 2 Solari less.',
    signetRingAbility: 'Into the Fray\nYou may take an Agent you sent this turn and deploy it to the Conflict as a 2 strength unit that can\'t be retreated.\nIf you have your Swordmaster: 3 strength instead.',
    complexity: 1,
  },
  {
    name: 'Chani',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: null,
    leaderAbility: 'Tactician\nWhenever you retreat or lose troops from the Conflict:\n· Advance your Tactics token that many spaces, earning rewards\n· Reset the token after reaching the end of the track',
    signetRingAbility: 'Fedaykin Maneuver\n· Retreat any number of your troops\n  OR\n· If you have 2+ Fremen Influence: Trade 1 Water for 2 Draws',
    complexity: 2,
  },
  {
    name: 'Piter de Vries',
    source: 'Bloodlines',
    compatibility: 'All',
    house: 'Harkonnen',
    startingEffect: 'Twisted Genius\nShuffle the Twisted Intrigue deck and place it face down near you.',
    leaderAbility: 'Twisted Genius\nRound Start:\n· Draw a Twisted Intrigue card\n(These count as Intrigue cards and can be stolen)',
    signetRingAbility: 'Harkonnen Advisor\n· +1 Troop\nYou can\'t deploy this troop to the Conflict this turn.',
    complexity: 2,
  },
  {
    name: 'Esmar Tuek',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: null,
    leaderAbility: 'Tuek\'s Sietch\nWhenever you send an Agent to Tuek\'s Sietch:\n· +1 Solari\nWhenever an opponent sends an Agent there:\n· +1 Intrigue',
    signetRingAbility: 'Smuggle Spice\n· Place 1 bonus spice on Tuek\'s Sietch\n  OR\n· Take 1 bonus spice from a Maker board space',
    complexity: 1,
  },
  {
    name: 'Steersman Y\'rkoon',
    source: 'Bloodlines',
    compatibility: 'All',
    house: null,
    startingEffect: 'Strange Form\nYou start the game with no Water and no Signet Ring in your deck.\n\nPlot Course\n· Shuffle the Navigation cards and draw five\n· Choose four to place face down above, in order\n· Return all others to the box\n· Whenever you reach 2 Influence with a Faction, play the next Navigation card (starting from the left)',
    leaderAbility: 'Hungry for Spice\nWhenever you gain 3+ spice in a single turn:\n· Draw 1 card',
    signetRingAbility: null,
    complexity: 3,
  },
  {
    name: 'Count Hasimir Fenring',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: 'Fenring',
    startingEffect: null,
    leaderAbility: 'Assassin\nWhenever you trash a card:\n· +1 Solari',
    signetRingAbility: 'Corrino Liaison\n· Trash a card in your play area\n  OR\n· Place 1 Spy with Deep Cover on the Emperor board area',
    complexity: 2,
  },
  {
    name: 'Gaius Helen Mohiam',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: null,
    startingEffect: null,
    leaderAbility: 'Clandestine\n· Each card you play has the Spy icon\n· Whenever you could recall a Spy to Gather Intelligence, you must',
    signetRingAbility: 'Listeners\n· Place 1 Spy on a Green space\n  OR\n· Pay 1 Spice → +1 Spy',
    complexity: 3,
  },
  {
    name: 'Liet Kynes',
    source: 'Bloodlines',
    compatibility: 'Uprising',
    house: null,
    startingEffect: null,
    leaderAbility: 'Arrakis Planetologist\n· Ignore the Influence requirement of Sietch Tabr\n· You summon no sandworms\n· For each one you would, instead: Trash 1 card, +1 Spice, +1 Intrigue\n(even when the Conflict is protected by the Shield Wall)',
    signetRingAbility: 'Judge of the Change\nIf you sent an Agent this turn to:\n· Green space + 2 Emperor Influence → +1 Water\n· Purple space → +1 Solari\n· Yellow space → +1 Spice',
    complexity: 3,
  },
  {
    name: 'Kota Odax of Ix',
    source: 'Bloodlines',
    compatibility: 'Rise of Ix OR Bloodlines',
    house: null,
    startingEffect: 'Secret Project\nPeek at the bottom Tech tile of each stack. Place one face down here.',
    leaderAbility: 'Secret Project\nWhenever you could acquire a Tech tile:\n· You may choose the one you set aside\n· It costs 1 Spice less',
    signetRingAbility: 'Reverse Engineering\n· +1 Spice\n  OR\n· Trash one of your Tech tiles → +1 Intrigue and Draw 1 card',
    complexity: 3,
  },
]

module.exports = leaderData
