'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const obj_crysknife_1 = require('./obj-crysknife-1.js')
const obj_crysknife_2 = require('./obj-crysknife-2.js')
const obj_desert_mouse_1 = require('./obj-desert-mouse-1.js')
const obj_desert_mouse_2 = require('./obj-desert-mouse-2.js')
const obj_ornithopter_1 = require('./obj-ornithopter-1.js')

module.exports = [
  obj_crysknife_1,
  obj_crysknife_2,
  obj_desert_mouse_1,
  obj_desert_mouse_2,
  obj_ornithopter_1,
]
