'use strict'

// AUTO-GENERATED by `npm run regen-card-indexes -w common`. Do not edit by hand.

const control_the_spice = require('./control-the-spice.js')
const convincing_argument = require('./convincing-argument.js')
const dagger = require('./dagger.js')
const diplomacy = require('./diplomacy.js')
const dune_the_desert_planet = require('./dune-the-desert-planet.js')
const experimentation = require('./experimentation.js')
const reconnaissance = require('./reconnaissance.js')
const seek_allies = require('./seek-allies.js')
const signet_ring = require('./signet-ring.js')

module.exports = [
  control_the_spice,
  convincing_argument,
  dagger,
  diplomacy,
  dune_the_desert_planet,
  experimentation,
  reconnaissance,
  seek_allies,
  signet_ring,
]
