module.exports =  [
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 1,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Consolidate Power',
    expansion: 'base game',
    value: 2,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Draw 2 Skill Cards of any type(s). They may come from outside you skill set'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 3,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 3,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 3,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 3,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 4,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 4,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Investigative Committee',
    expansion: 'base game',
    value: 5,
    politics: true,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All Skill Cards are played face up during this skill check (including from the Destiny deck)'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Executive Order',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Choose any other player. He may move his character and then take 1 action OR not move and take 2 actions. Limit of 1 "Executive Order" card used per turn'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Declare Emergency',
    expansion: 'base game',
    value: 5,
    politics: false,
    leadership: true,
    tactics: false,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after strength is totaled in a skill check to reduce its difficulty by 2. Limit of 1 "Declare Emergency" card used per skill check'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Launch Scout',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Risk 1 raptor to roll a die. If 3 or higher, look at the top card of the Crisis or Destination deck and place it on the top or the bottom. Otherwise, destroy 1 raptor'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Strategic Planning',
    expansion: 'base game',
    value: 5,
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play before any die roll to add 2 to the result. Limit of 1 "Strategic Planning" card used per die roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Evasive Maneuvers',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Play after any viper is attacked to reroll the die. If the viper is piloted, subtract 2 from the new roll'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 4,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Maximum Firepower',
    expansion: 'base game',
    value: 5,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: true,
    engineering: false,
    treachery: false,
    consequence: '',
    text: 'Action: Play while piloting a viper to attack up to 4 times'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 1,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Repair',
    expansion: 'base game',
    value: 2,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Action: Repair your current location or if you are in the "Hangar Deck" location, you may repair up to 2 damaged vipers'
  },
  {
    name: 'Scientific Research',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All engineering cards in the skill check count as positive strength'
  },
  {
    name: 'Scientific Research',
    expansion: 'base game',
    value: 3,
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: true,
    treachery: false,
    consequence: '',
    text: 'Play before cards are added to a skill check. All engineering cards in the skill check count as positive strength'
  },
  ... 139 more items
]
