module.exports =  [
  {
    name: 'Massive Assault',
    expansion: 'base game',
    type: 'Cylon Attack',
    'cylon activation': 'Hvy Raiders, Basestar Attacks',
    'skill check value': '',
    'pass effect': '',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': 'Power Failure: Move the fleet token 2 spaces towards the start of the Jump Preparation track',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    'total basestars': 2,
    'total heavy raiders': 1,
    'total raiders': 6,
    'total vipers': 2,
    'total civvies': 4,
    'basestars sector 1': 0,
    'basestars sector 2': 1,
    'basestars sector 3': 1,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 1,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 4,
    'raiders sector 3': 2,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 1,
    'vipers sector 6': 1,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 2,
    'civvies sector 6': 2
  },
  {
    name: 'Bomb on Colony 1',
    expansion: 'base game',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '15',
    'pass effect': 'No Effect',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': '-2 morale, and all characters on Colonial One are sent to "Sickbay". Keep this card in play. Characters may not move to Colonial One for the rest of the game',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: false,
    tactics: true,
    piloting: true,
    engineering: true,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Cylon Intruders',
    expansion: 'base game',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '18',
    'pass effect': 'No Effect',
    'partial pass value': '14',
    'partial pass effect': 'Place 1 centurion marker at the star of the Boarding Party track',
    'fail effect / choose option 1 / cac effect': 'Damage Galactica and place 2 centurion markers at the start of the Boarding Party track',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Fleet Mobilization',
    expansion: 'base game',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '24',
    'pass effect': 'Activate: Basestar Attacks, Raiders Launch',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': '-1 morale and activate: Basestar Attacks, Raiders, Hvy Raiders, Raiders Launch',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: true,
    engineering: true,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Inbound Nukes',
    expansion: 'base game',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '15',
    'pass effect': 'No Effect',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': '-1 fuel, -1 food, and -1 population',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Fighting Blind',
    expansion: 'exodus',
    type: 'Choice',
    'cylon activation': '',
    'skill check value': '',
    'pass effect': '',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': 'Place 2 centurions at the start of the Boarding Party track',
    'choose option 2': 'The CAG is executed',
    consequence: '',
    'who chooses?': 'CAG',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Fire All Missiles',
    expansion: 'exodus',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '22',
    'pass effect': 'No Effect',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': 'Draw 2 civilian ships to destroy',
    'choose option 2': '',
    consequence: 'Damage Galactica twice',
    'who chooses?': '',
    politics: false,
    leadership: false,
    tactics: true,
    piloting: true,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Human Prisoner',
    expansion: 'exodus',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '18',
    'pass effect': 'No Effect',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': `The Cylon player who played this card chooses one human player and takes allof his Skill Cards. That human player's character is then sent to "Sickbay"`,
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: '"Demand Peace" Manifesto',
    expansion: 'pegasus',
    type: 'Choice',
    'cylon activation': '',
    'skill check value': '',
    'pass effect': '',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': '-1 morale and damage Galactica twice',
    'choose option 2': 'The president and the Admiral each discard their hand of Skill Cards',
    consequence: '',
    'who chooses?': 'Admiral',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Psychological Warfare',
    expansion: 'pegasus',
    type: 'Choice',
    'cylon activation': '',
    'skill check value': '',
    'pass effect': '',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': '-1 morale, each player discards 2 Skill Cards and draws 2 Treachery Cards',
    'choose option 2': 'Each revealed Cylon player draws 2 Treachery Cards. Then, discard the entire Destiny deck and build a new one consisting of only 6 Treachery Cards',
    consequence: '',
    'who chooses?': 'President',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'Lured into a Trap',
    expansion: 'pegasus',
    type: 'Cylon Attack',
    'cylon activation': 'Raiders',
    'skill check value': '',
    'pass effect': '',
    'partial pass value': '',
    'partial pass effect': '',
    'fail effect / choose option 1 / cac effect': 'Dangerous Reparis are Necessary: Keep this card in play until after the fleet jumps. Any character in either the "Engine Room" or "FTL Control" location when the fleet jumps is executed',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: false,
    tactics: false,
    piloting: false,
    engineering: false,
    'total basestars': 2,
    'total heavy raiders': 1,
    'total raiders': 6,
    'total vipers': 2,
    'total civvies': 2,
    'basestars sector 1': 0,
    'basestars sector 2': 1,
    'basestars sector 3': 1,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 1,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 3,
    'raiders sector 3': 3,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 1,
    'vipers sector 6': 1,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 1,
    'civvies sector 6': 1
  },
  {
    name: 'Footage Transmitted',
    expansion: 'pegasus',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '17',
    'pass effect': 'Each player draws 1 Treachery Card',
    'partial pass value': '12',
    'partial pass effect': 'Each revealed Cylon player draws 2 Treachery Cards',
    'fail effect / choose option 1 / cac effect': 'Each revealed Cylon player draws 2 Treachery Cards and 1 Super Crisis Card',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: true,
    leadership: true,
    tactics: true,
    piloting: false,
    engineering: false,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  },
  {
    name: 'The Farm',
    expansion: 'pegasus',
    type: 'Skill Check',
    'cylon activation': '',
    'skill check value': '15',
    'pass effect': 'No Effect',
    'partial pass value': '8',
    'partial pass effect': '-1 food',
    'fail effect / choose option 1 / cac effect': '-1 food, -1 population. Keep this card in play. Human players may not use their once-per-game abilities',
    'choose option 2': '',
    consequence: '',
    'who chooses?': '',
    politics: false,
    leadership: false,
    tactics: true,
    piloting: false,
    engineering: true,
    'total basestars': 0,
    'total heavy raiders': 0,
    'total raiders': 0,
    'total vipers': 0,
    'total civvies': 0,
    'basestars sector 1': 0,
    'basestars sector 2': 0,
    'basestars sector 3': 0,
    'basestars sector 4': 0,
    'basestars sector 5': 0,
    'basestars sector 6': 0,
    'heavy raiders sector 1': 0,
    'heavy raiders sector 2': 0,
    'heavy raiders sector 3': 0,
    'heavy raiders sector 4': 0,
    'heavy raiders sector 5': 0,
    'heavy raiders sector 6': 0,
    'raiders sector 1': 0,
    'raiders sector 2': 0,
    'raiders sector 3': 0,
    'raiders sector 4': 0,
    'raiders sector 5': 0,
    'raiders sector 6': 0,
    'vipers sector 1': 0,
    'vipers sector 2': 0,
    'vipers sector 3': 0,
    'vipers sector 4': 0,
    'vipers sector 5': 0,
    'vipers sector 6': 0,
    'civvies sector 1': 0,
    'civvies sector 2': 0,
    'civvies sector 3': 0,
    'civvies sector 4': 0,
    'civvies sector 5': 0,
    'civvies sector 6': 0
  }
]
