#!/bin/sh

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if api folder has changes
if echo "$STAGED_FILES" | grep -q "^api/"; then
  cd api

  echo "Running tests for api..."
  npm run test

  echo "Running lint for api..."
  npm run lint

  cd ..
fi

# Check if app folder has changes
if echo "$STAGED_FILES" | grep -q "^app/"; then
  cd app

  echo "Running lint for app..."
  npm run lint

  cd ..
fi

# Check if common folder has changes
if echo "$STAGED_FILES" | grep -q "^common/"; then
  cd common

  echo "Running tests for common..."
  npm run test

  echo "Running lint for common..."
  npm run lint

  cd ..
fi
