#!/bin/sh

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only)

# Check if api folder has changes
if echo "$STAGED_FILES" | grep -q "^api/"; then
  echo "Running lint for api..."
  cd api && npm run lint && cd ..
fi

# Check if app folder has changes
if echo "$STAGED_FILES" | grep -q "^app/"; then
  echo "Running lint for app..."
  cd app && npm run lint && cd ..
fi

# Check if common folder has changes
if echo "$STAGED_FILES" | grep -q "^common/"; then
  echo "Running lint for common..."
  cd common && npm run lint && cd ..
fi
